// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type KnowledgeAssistantInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	ProviderConfig *KnowledgeAssistantProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type KnowledgeAssistantObservation struct {
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	Creator *string `json:"creator,omitempty" tf:"creator,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	EndpointName *string `json:"endpointName,omitempty" tf:"endpoint_name,omitempty"`

	ErrorInfo *string `json:"errorInfo,omitempty" tf:"error_info,omitempty"`

	ExperimentID *string `json:"experimentId,omitempty" tf:"experiment_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	ProviderConfig *KnowledgeAssistantProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type KnowledgeAssistantParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +kubebuilder:validation:Optional
	Instructions *string `json:"instructions,omitempty" tf:"instructions,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderConfig *KnowledgeAssistantProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`
}

type KnowledgeAssistantProviderConfigInitParameters struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type KnowledgeAssistantProviderConfigObservation struct {
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type KnowledgeAssistantProviderConfigParameters struct {

	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

// KnowledgeAssistantSpec defines the desired state of KnowledgeAssistant
type KnowledgeAssistantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KnowledgeAssistantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KnowledgeAssistantInitParameters `json:"initProvider,omitempty"`
}

// KnowledgeAssistantStatus defines the observed state of KnowledgeAssistant.
type KnowledgeAssistantStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               KnowledgeAssistantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KnowledgeAssistant is the Schema for the KnowledgeAssistants API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type KnowledgeAssistant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	Spec   KnowledgeAssistantSpec   `json:"spec"`
	Status KnowledgeAssistantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KnowledgeAssistantList contains a list of KnowledgeAssistants
type KnowledgeAssistantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KnowledgeAssistant `json:"items"`
}

// Repository type metadata.
var (
	KnowledgeAssistant_Kind             = "KnowledgeAssistant"
	KnowledgeAssistant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KnowledgeAssistant_Kind}.String()
	KnowledgeAssistant_KindAPIVersion   = KnowledgeAssistant_Kind + "." + CRDGroupVersion.String()
	KnowledgeAssistant_GroupVersionKind = CRDGroupVersion.WithKind(KnowledgeAssistant_Kind)
)

func init() {
	SchemeBuilder.Register(&KnowledgeAssistant{}, &KnowledgeAssistantList{})
}
