# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: postgres.databricks.m.crossplane.io/v1beta1
kind: PostgresProject
metadata:
  annotations:
    meta.upbound.io/example-id: postgres/v1beta1/postgresproject
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    projectId: my-project
    spec:
      displayName: My Application Project
      pgVersion: 17
