// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package namespaced

import (
	"github.com/glalanne/provider-databricks/config/namespaced/access_control_rule_set"
	"github.com/glalanne/provider-databricks/config/namespaced/alert"
<<<<<<< HEAD

	// "github.com/glalanne/provider-databricks/config/namespaced/app"
=======
>>>>>>> 22d3f447638c67622a710bb969a42a932ffdb1af
	"github.com/glalanne/provider-databricks/config/namespaced/artifact_allowlist"
	"github.com/glalanne/provider-databricks/config/namespaced/budget"
	"github.com/glalanne/provider-databricks/config/namespaced/catalog"
	"github.com/glalanne/provider-databricks/config/namespaced/catalog_workspace_binding"
	"github.com/glalanne/provider-databricks/config/namespaced/cluster"
	"github.com/glalanne/provider-databricks/config/namespaced/cluster_policy"
	"github.com/glalanne/provider-databricks/config/namespaced/compliance_security_profile_workspace_setting"
	"github.com/glalanne/provider-databricks/config/namespaced/connection"
	"github.com/glalanne/provider-databricks/config/namespaced/credential"
	"github.com/glalanne/provider-databricks/config/namespaced/custom_app_integration"
	"github.com/glalanne/provider-databricks/config/namespaced/dashboard"
	"github.com/glalanne/provider-databricks/config/namespaced/dbfs_file"
	"github.com/glalanne/provider-databricks/config/namespaced/default_namespace_setting"
	"github.com/glalanne/provider-databricks/config/namespaced/directory"
	"github.com/glalanne/provider-databricks/config/namespaced/enhanced_security_monitoring_workspace_setting"
	"github.com/glalanne/provider-databricks/config/namespaced/entitlements"
	"github.com/glalanne/provider-databricks/config/namespaced/external_location"
	"github.com/glalanne/provider-databricks/config/namespaced/file"
	"github.com/glalanne/provider-databricks/config/namespaced/git_credential"
	"github.com/glalanne/provider-databricks/config/namespaced/global_init_script"
	"github.com/glalanne/provider-databricks/config/namespaced/grant"
	"github.com/glalanne/provider-databricks/config/namespaced/grants"
	"github.com/glalanne/provider-databricks/config/namespaced/group"
	"github.com/glalanne/provider-databricks/config/namespaced/group_instance_profile"
	"github.com/glalanne/provider-databricks/config/namespaced/group_member"
	"github.com/glalanne/provider-databricks/config/namespaced/group_role"
	"github.com/glalanne/provider-databricks/config/namespaced/instance_pool"
	"github.com/glalanne/provider-databricks/config/namespaced/instance_profile"
	"github.com/glalanne/provider-databricks/config/namespaced/ip_access_list"
	"github.com/glalanne/provider-databricks/config/namespaced/job"
	"github.com/glalanne/provider-databricks/config/namespaced/lakehouse_monitor"
	"github.com/glalanne/provider-databricks/config/namespaced/library"
	"github.com/glalanne/provider-databricks/config/namespaced/metastore"
	"github.com/glalanne/provider-databricks/config/namespaced/metastore_assignment"
	"github.com/glalanne/provider-databricks/config/namespaced/metastore_data_access"
	"github.com/glalanne/provider-databricks/config/namespaced/mlflow_experiment"
	"github.com/glalanne/provider-databricks/config/namespaced/mlflow_model"
	"github.com/glalanne/provider-databricks/config/namespaced/mlflow_webhook"
	"github.com/glalanne/provider-databricks/config/namespaced/model_serving"
	"github.com/glalanne/provider-databricks/config/namespaced/mount"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_credentials"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_customer_managed_keys"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_log_delivery"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_ncc_binding"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_ncc_private_endpoint_rule"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_network_connectivity_config"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_networks"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_permission_assignment"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_private_access_settings"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_storage_configurations"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_vpc_endpoint"
	"github.com/glalanne/provider-databricks/config/namespaced/mws_workspaces"
	"github.com/glalanne/provider-databricks/config/namespaced/notebook"
	"github.com/glalanne/provider-databricks/config/namespaced/notification_destination"
	"github.com/glalanne/provider-databricks/config/namespaced/obo_token"
	"github.com/glalanne/provider-databricks/config/namespaced/online_table"
	"github.com/glalanne/provider-databricks/config/namespaced/permission_assignment"
	"github.com/glalanne/provider-databricks/config/namespaced/permissions"
	"github.com/glalanne/provider-databricks/config/namespaced/pipeline"
	"github.com/glalanne/provider-databricks/config/namespaced/provider"
	"github.com/glalanne/provider-databricks/config/namespaced/quality_monitor"
	"github.com/glalanne/provider-databricks/config/namespaced/query"
	"github.com/glalanne/provider-databricks/config/namespaced/recipient"
	"github.com/glalanne/provider-databricks/config/namespaced/registered_model"
	"github.com/glalanne/provider-databricks/config/namespaced/repo"
	"github.com/glalanne/provider-databricks/config/namespaced/restrict_workspace_admins_setting"
	"github.com/glalanne/provider-databricks/config/namespaced/schema"
	"github.com/glalanne/provider-databricks/config/namespaced/secret"
	"github.com/glalanne/provider-databricks/config/namespaced/secret_acl"
	"github.com/glalanne/provider-databricks/config/namespaced/secret_scope"
	"github.com/glalanne/provider-databricks/config/namespaced/service_principal"
	"github.com/glalanne/provider-databricks/config/namespaced/service_principal_role"
	"github.com/glalanne/provider-databricks/config/namespaced/service_principal_secret"
	"github.com/glalanne/provider-databricks/config/namespaced/share"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_alert"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_dashboard"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_endpoint"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_global_config"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_permissions"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_query"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_table"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_visualization"
	"github.com/glalanne/provider-databricks/config/namespaced/sql_widget"
	"github.com/glalanne/provider-databricks/config/namespaced/storage_credential"
	"github.com/glalanne/provider-databricks/config/namespaced/system_schema"
	"github.com/glalanne/provider-databricks/config/namespaced/token"
	"github.com/glalanne/provider-databricks/config/namespaced/user"
	"github.com/glalanne/provider-databricks/config/namespaced/user_instance_profile"
	"github.com/glalanne/provider-databricks/config/namespaced/user_role"
	"github.com/glalanne/provider-databricks/config/namespaced/vector_search_endpoint"
	"github.com/glalanne/provider-databricks/config/namespaced/vector_search_index"
	"github.com/glalanne/provider-databricks/config/namespaced/volume"
	"github.com/glalanne/provider-databricks/config/namespaced/workspace_binding"
	"github.com/glalanne/provider-databricks/config/namespaced/workspace_conf"
	"github.com/glalanne/provider-databricks/config/namespaced/workspace_file"
)

func init() {
<<<<<<< HEAD
	// ProviderConfiguration.AddConfig(app.Configure) // TODO: waiting on protov6 support with Upjet https://github.com/crossplane/upjet/issues/372
=======
>>>>>>> 22d3f447638c67622a710bb969a42a932ffdb1af
	ProviderConfiguration.AddConfig(cluster.Configure)
	ProviderConfiguration.AddConfig(cluster_policy.Configure)
	ProviderConfiguration.AddConfig(credential.Configure)
	ProviderConfiguration.AddConfig(token.Configure)
	ProviderConfiguration.AddConfig(secret.Configure)
	ProviderConfiguration.AddConfig(secret_scope.Configure)
	ProviderConfiguration.AddConfig(notebook.Configure)
	ProviderConfiguration.AddConfig(job.Configure)
	ProviderConfiguration.AddConfig(instance_pool.Configure)
	ProviderConfiguration.AddConfig(permissions.Configure)
	ProviderConfiguration.AddConfig(sql_endpoint.Configure)
	ProviderConfiguration.AddConfig(entitlements.Configure)
	ProviderConfiguration.AddConfig(group.Configure)
	ProviderConfiguration.AddConfig(group_member.Configure)
	ProviderConfiguration.AddConfig(group_role.Configure)
	ProviderConfiguration.AddConfig(ip_access_list.Configure)
	ProviderConfiguration.AddConfig(permission_assignment.Configure)
	ProviderConfiguration.AddConfig(service_principal.Configure)
	ProviderConfiguration.AddConfig(service_principal_role.Configure)
	ProviderConfiguration.AddConfig(sql_permissions.Configure)
	ProviderConfiguration.AddConfig(grants.Configure)
	ProviderConfiguration.AddConfig(pipeline.Configure)
	ProviderConfiguration.AddConfig(alert.Configure)
	ProviderConfiguration.AddConfig(query.Configure)
	ProviderConfiguration.AddConfig(sql_alert.Configure)
	ProviderConfiguration.AddConfig(sql_dashboard.Configure)
	ProviderConfiguration.AddConfig(sql_global_config.Configure)
	ProviderConfiguration.AddConfig(sql_query.Configure)
	ProviderConfiguration.AddConfig(sql_table.Configure)
	ProviderConfiguration.AddConfig(budget.Configure)
	ProviderConfiguration.AddConfig(git_credential.Configure)
	ProviderConfiguration.AddConfig(catalog.Configure)
	ProviderConfiguration.AddConfig(connection.Configure)
	ProviderConfiguration.AddConfig(external_location.Configure)
	ProviderConfiguration.AddConfig(schema.Configure)
	ProviderConfiguration.AddConfig(library.Configure)
	ProviderConfiguration.AddConfig(sql_visualization.Configure)
	ProviderConfiguration.AddConfig(sql_widget.Configure)
	ProviderConfiguration.AddConfig(provider.Configure)
	ProviderConfiguration.AddConfig(mlflow_experiment.Configure)
	ProviderConfiguration.AddConfig(mlflow_model.Configure)
	ProviderConfiguration.AddConfig(mlflow_webhook.Configure)
	ProviderConfiguration.AddConfig(model_serving.Configure)
	ProviderConfiguration.AddConfig(access_control_rule_set.Configure)
	ProviderConfiguration.AddConfig(artifact_allowlist.Configure)
	ProviderConfiguration.AddConfig(catalog_workspace_binding.Configure)
	ProviderConfiguration.AddConfig(compliance_security_profile_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(custom_app_integration.Configure)
	ProviderConfiguration.AddConfig(dashboard.Configure)
	ProviderConfiguration.AddConfig(dbfs_file.Configure)
	ProviderConfiguration.AddConfig(default_namespace_setting.Configure)
	ProviderConfiguration.AddConfig(directory.Configure)
	ProviderConfiguration.AddConfig(enhanced_security_monitoring_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(file.Configure)
	ProviderConfiguration.AddConfig(global_init_script.Configure)
	ProviderConfiguration.AddConfig(grant.Configure)
	ProviderConfiguration.AddConfig(group_instance_profile.Configure)
	ProviderConfiguration.AddConfig(instance_profile.Configure)
	ProviderConfiguration.AddConfig(lakehouse_monitor.Configure)
	ProviderConfiguration.AddConfig(metastore.Configure)
	ProviderConfiguration.AddConfig(metastore_assignment.Configure)
	ProviderConfiguration.AddConfig(metastore_data_access.Configure)
	ProviderConfiguration.AddConfig(mount.Configure)
	ProviderConfiguration.AddConfig(mws_credentials.Configure)
	ProviderConfiguration.AddConfig(mws_customer_managed_keys.Configure)
	ProviderConfiguration.AddConfig(mws_log_delivery.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_binding.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_private_endpoint_rule.Configure)
	ProviderConfiguration.AddConfig(mws_network_connectivity_config.Configure)
	ProviderConfiguration.AddConfig(mws_networks.Configure)
	ProviderConfiguration.AddConfig(mws_permission_assignment.Configure)
	ProviderConfiguration.AddConfig(mws_private_access_settings.Configure)
	ProviderConfiguration.AddConfig(mws_storage_configurations.Configure)
	ProviderConfiguration.AddConfig(mws_vpc_endpoint.Configure)
	ProviderConfiguration.AddConfig(mws_workspaces.Configure)
	ProviderConfiguration.AddConfig(notification_destination.Configure)
	ProviderConfiguration.AddConfig(obo_token.Configure)
	ProviderConfiguration.AddConfig(online_table.Configure)
	ProviderConfiguration.AddConfig(quality_monitor.Configure)
	ProviderConfiguration.AddConfig(recipient.Configure)
	ProviderConfiguration.AddConfig(registered_model.Configure)
	ProviderConfiguration.AddConfig(repo.Configure)
	ProviderConfiguration.AddConfig(restrict_workspace_admins_setting.Configure)
	ProviderConfiguration.AddConfig(secret_acl.Configure)
	ProviderConfiguration.AddConfig(service_principal_secret.Configure)
	ProviderConfiguration.AddConfig(share.Configure)
	ProviderConfiguration.AddConfig(storage_credential.Configure)
	ProviderConfiguration.AddConfig(system_schema.Configure)
	ProviderConfiguration.AddConfig(user.Configure)
	ProviderConfiguration.AddConfig(user_instance_profile.Configure)
	ProviderConfiguration.AddConfig(user_role.Configure)
	ProviderConfiguration.AddConfig(vector_search_endpoint.Configure)
	ProviderConfiguration.AddConfig(vector_search_index.Configure)
	ProviderConfiguration.AddConfig(volume.Configure)
	ProviderConfiguration.AddConfig(workspace_binding.Configure)
	ProviderConfiguration.AddConfig(workspace_conf.Configure)
	ProviderConfiguration.AddConfig(workspace_file.Configure)
}
