apiVersion: sql.databricks.crossplane.io/v1alpha1
kind: Query
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/query
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    displayName: My Query Name
    parentPathSelector:
      matchLabels:
        testing.upbound.io/example-name: shared_dir
    queryText: SELECT 42 as value
    warehouseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: workspace.databricks.crossplane.io/v1alpha1
kind: Directory
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/query
  labels:
    testing.upbound.io/example-name: shared_dir
  name: shared-dir
spec:
  forProvider:
    path: /Shared/Queries
