apiVersion: sql.databricks.crossplane.io/v1alpha1
kind: SQLQuery
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sqlquery
  labels:
    testing.upbound.io/example-name: q1
  name: q1
spec:
  forProvider:
    dataSourceId: ${databricks_sql_endpoint.example.data_source_id}
    name: My Query Name
    parameter:
    - name: p1
      text:
      - value: default
      title: Title for p1
    - enum:
      - multiple:
        - prefix: '"'
          separator: ','
          suffix: '"'
        options:
        - default
        - foo
        - bar
        value: default
      name: p2
      title: Title for p2
    - date:
      - value: "2022-01-01"
      name: p3
      title: Title for p3
    parent: folders/${databricks_directory.shared_dir.object_id}
    query: |2
                              SELECT {{ p1 }} AS p1
                              WHERE 1=1
                              AND p2 in ({{ p2 }})
                              AND event_date > date '{{ p3 }}'
    runAsRole: viewer
    tags:
    - t1
    - t2

---

apiVersion: workspace.databricks.crossplane.io/v1alpha1
kind: Directory
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sqlquery
  labels:
    testing.upbound.io/example-name: shared_dir
  name: shared-dir
spec:
  forProvider:
    path: /Shared/Queries
