apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/group
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    allowClusterCreate: true
    allowInstancePoolCreate: true
    displayName: Some Group
