apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: SecretACL
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: my_secret_acl
  name: my-secret-acl
  namespace: upbound-system
spec:
  forProvider:
    permission: READ
    principalSelector:
      matchLabels:
        testing.upbound.io/example-name: ds
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: app

---

apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: ds
  name: ds
  namespace: upbound-system
spec:
  forProvider:
    displayName: data-scientists

---

apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: publishing_api
  name: publishing-api
  namespace: upbound-system
spec:
  forProvider:
    key: publishing_api
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: app
    stringValueSecretRef:
      key: attribute.example.value
      name: example-

---

apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secretacl
  labels:
    testing.upbound.io/example-name: app
  name: app
  namespace: upbound-system
spec:
  forProvider:
    name: app-secret-scope
