apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: publishing_api
  name: publishing-api
  namespace: upbound-system
spec:
  forProvider:
    key: publishing_api
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: app
    stringValueSecretRef:
      key: attribute.example.value
      name: example-

---

apiVersion: compute.databricks.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    sparkConf:
      fs.azure.account.oauth2.client.secret: ${databricks_secret.publishing_api.config_reference}

---

apiVersion: security.databricks.m.crossplane.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: app
  name: app
  namespace: upbound-system
spec:
  forProvider:
    name: application-secret-scope
