apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: ExternalLocation
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/externallocation
  labels:
    testing.upbound.io/example-name: some
  name: some
spec:
  forProvider:
    comment: Managed by TF
    credentialName: ${databricks_storage_credential.external.id}
    name: external
    url: s3://${aws_s3_bucket.external.id}/some

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: StorageCredential
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/externallocation
  labels:
    testing.upbound.io/example-name: external
  name: external
spec:
  forProvider:
    awsIamRole:
    - roleArn: ${aws_iam_role.external_data_access.arn}
    comment: Managed by TF
    name: ${aws_iam_role.external_data_access.name}
