apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: StorageCredential
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/storagecredential
  labels:
    testing.upbound.io/example-name: external
  name: external
spec:
  forProvider:
    awsIamRole:
    - roleArn: ${aws_iam_role.external_data_access.arn}
    comment: Managed by TF
    name: ${aws_iam_role.external_data_access.name}

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Grants
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/storagecredential
  labels:
    testing.upbound.io/example-name: external_creds
  name: external-creds
spec:
  forProvider:
    grant:
    - principal: Data Engineers
      privileges:
      - CREATE_EXTERNAL_TABLE
    storageCredential: ${databricks_storage_credential.external.id}
