version: "2"
run:
  concurrency: 4
linters:
  enable:
    - govet
    - gocyclo
    - gocritic
    - goconst
    - goimports
    - gofmt  # We enable this as well as goimports for its simplify mode.
    - gosimple
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - misspell
    - nakedret
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - io/ioutil.ReadFile
        - io/ioutil.ReadDir
        - io/ioutil.ReadAll
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10
    lll:
      tab-width: 1
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      confidence: 0.8
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - misspell
          - typecheck
        path: zz_.+\.go$
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - scopelint
          - unparam
        path: _test(ing)?\.go
      - linters:
          - revive
        path: config.+config\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gocritic
        text: '(hugeParam|rangeValCopy):'
      - linters:
          - staticcheck
        text: 'SA3000:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
    paths:
      - zz_.*go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/glalanne/provider-databricks
  exclusions:
    generated: lax
    paths:
      - zz_.*go$
      - third_party$
      - builtin$
      - examples$
