apiVersion: databricks.crossplane.io/v1alpha1
kind: Alert
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/alert
  labels:
    testing.upbound.io/example-name: alert
  name: alert
spec:
  forProvider:
    condition:
    - op: GREATER_THAN
      operand:
      - column:
        - name: value
      threshold:
      - value:
        - doubleValue: 42
    displayName: TF new alert
    parentPath: ${databricks_directory.shared_dir.path}
    queryId: ${databricks_query.this.id}

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Query
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/alert
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    displayName: My Query Name
    parentPath: /Shared/Queries
    queryText: SELECT 42 as value
    warehouseId: ${databricks_sql_endpoint.example.id}
