apiVersion: databricks.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: mysql
  name: mysql
spec:
  forProvider:
    comment: this is a connection to mysql db
    connectionType: MYSQL
    name: mysql_connection
    optionsSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    properties:
      purpose: testing
