apiVersion: databricks.crossplane.io/v1alpha1
kind: ExternalLocation
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/externallocation
  labels:
    testing.upbound.io/example-name: some
  name: some
spec:
  forProvider:
    comment: Managed by TF
    credentialName: ${databricks_storage_credential.external.id}
    name: external
    url: s3://${aws_s3_bucket.external.id}/some

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Grants
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/externallocation
  labels:
    testing.upbound.io/example-name: some
  name: some
spec:
  forProvider:
    externalLocation: ${databricks_external_location.some.id}
    grant:
    - principal: Data Engineers
      privileges:
      - CREATE_EXTERNAL_TABLE
      - READ_FILES
