apiVersion: databricks.crossplane.io/v1alpha1
kind: MwsLogDelivery
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/mwslogdelivery
  labels:
    testing.upbound.io/example-name: usage_logs
  name: usage-logs
spec:
  forProvider:
    accountId: ${var.databricks_account_id}
    configName: Usage Logs
    credentialsId: ${databricks_mws_credentials.log_writer.credentials_id}
    deliveryPathPrefix: billable-usage
    logType: BILLABLE_USAGE
    outputFormat: CSV
    storageConfigurationId: ${databricks_mws_storage_configurations.log_bucket.storage_configuration_id}

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: MwsCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/mwslogdelivery
  labels:
    testing.upbound.io/example-name: log_writer
  name: log-writer
spec:
  forProvider:
    accountId: ${var.databricks_account_id}
    credentialsName: Usage Delivery
    roleArn: ${aws_iam_role.logdelivery.arn}

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: MwsStorageConfigurations
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/mwslogdelivery
  labels:
    testing.upbound.io/example-name: log_bucket
  name: log-bucket
spec:
  forProvider:
    accountIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    bucketName: ${var.prefix}-logdelivery
    storageConfigurationName: Usage Logs
