apiVersion: databricks.crossplane.io/v1alpha1
kind: OboToken
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/obotoken
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    applicationId: ${databricks_service_principal.this.application_id}
    comment: PAT on behalf of ${databricks_service_principal.this.display_name}
    lifetimeSeconds: 3600

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/obotoken
  labels:
    testing.upbound.io/example-name: token_usage
  name: token-usage
spec:
  forProvider:
    accessControl:
    - permissionLevel: CAN_USE
      servicePrincipalNameSelector:
        matchLabels:
          testing.upbound.io/example-name: this
    authorization: tokens

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: ServicePrincipal
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/obotoken
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    displayName: Automation-only SP
