apiVersion: databricks.crossplane.io/v1alpha1
kind: Repo
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/repo
  labels:
    testing.upbound.io/example-name: nutter_in_home
  name: nutter-in-home
spec:
  forProvider:
    url: https://github.com/user/demo.git
