apiVersion: databricks.crossplane.io/v1alpha1
kind: Share
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/share
  labels:
    testing.upbound.io/example-name: some
  name: some
spec:
  forProvider:
    dynamic:
      object:
      - content:
        - data_object_type: TABLE
          name: ${object.value}
        for_each: ${data.databricks_tables.things.ids}
    name: my_share
