apiVersion: databricks.crossplane.io/v1alpha1
kind: SQLAlert
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqlalert
  labels:
    testing.upbound.io/example-name: alert
  name: alert
spec:
  forProvider:
    name: My Alert
    options:
    - column: p1
      muted: false
      op: ==
      value: "2"
    parent: folders/${databricks_directory.shared_dir.object_id}
    queryId: ${databricks_sql_query.this.id}
    rearm: 1

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Directory
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqlalert
  labels:
    testing.upbound.io/example-name: shared_dir
  name: shared-dir
spec:
  forProvider:
    path: /Shared/Queries

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: SQLQuery
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqlalert
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    dataSourceId: ${databricks_sql_endpoint.example.data_source_id}
    name: My Query Name
    parent: folders/${databricks_directory.shared_dir.object_id}
    query: SELECT 1 AS p1, 2 as p2
