apiVersion: databricks.crossplane.io/v1alpha1
kind: SqlEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqlendpoint
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    clusterSize: Small
    maxNumClusters: 1
    name: Endpoint of ${data.databricks_current_user.me.alphanumeric}
    tags:
    - customTags:
      - key: City
        value: Amsterdam
