apiVersion: databricks.crossplane.io/v1alpha1
kind: SQLTable
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: thing
  name: thing
spec:
  forProvider:
    catalogName: sandbox
    column:
    - name: id
      type: int
    - comment: name of thing
      name: name
      type: string
    comment: this table is managed by terraform
    dataSourceFormat: DELTA
    name: quickstart_table
    provider: ${databricks.workspace}
    schemaName: things
    storageLocation: ""
    tableType: MANAGED

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    comment: this catalog is managed by terraform
    name: sandbox
    properties:
      purpose: testing

---

apiVersion: databricks.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: databricks/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: things
  name: things
spec:
  forProvider:
    catalogName: ${databricks_catalog.sandbox.id}
    comment: this database is managed by terraform
    name: things
    properties:
      kind: various
