apiVersion: security.databricks.crossplane.io/v1alpha1
kind: ServicePrincipalSecret
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/serviceprincipalsecret
  labels:
    testing.upbound.io/example-name: terraform_sp
  name: terraform-sp
spec:
  forProvider:
    servicePrincipalId: ${databricks_service_principal.this.id}
