// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AutomaticClusterUpdateWorkspaceEnablementDetailsInitParameters struct {

	// The feature is force enabled if compliance mode is active
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type AutomaticClusterUpdateWorkspaceEnablementDetailsObservation struct {

	// The feature is force enabled if compliance mode is active
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type AutomaticClusterUpdateWorkspaceEnablementDetailsParameters struct {

	// The feature is force enabled if compliance mode is active
	// +kubebuilder:validation:Optional
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	// +kubebuilder:validation:Optional
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	// +kubebuilder:validation:Optional
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowInitParameters struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	WeekDayBasedSchedule *AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleInitParameters `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowObservation struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	WeekDayBasedSchedule *AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleObservation `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowParameters struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	// +kubebuilder:validation:Optional
	WeekDayBasedSchedule *AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleParameters `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleInitParameters struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	WindowStartTime *MaintenanceWindowWeekDayBasedScheduleWindowStartTimeInitParameters `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleObservation struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	WindowStartTime *MaintenanceWindowWeekDayBasedScheduleWindowStartTimeObservation `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type AutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleParameters struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	// +kubebuilder:validation:Optional
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	// +kubebuilder:validation:Optional
	WindowStartTime *MaintenanceWindowWeekDayBasedScheduleWindowStartTimeParameters `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleInitParameters struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	WindowStartTime *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeInitParameters `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleObservation struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	WindowStartTime *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeObservation `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleParameters struct {

	// Possible values are: FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY
	// +kubebuilder:validation:Optional
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`

	// Possible values are: EVERY_WEEK, FIRST_AND_THIRD_OF_MONTH, FIRST_OF_MONTH, FOURTH_OF_MONTH, SECOND_AND_FOURTH_OF_MONTH, SECOND_OF_MONTH, THIRD_OF_MONTH
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindowWindowStartTime, optional)
	// +kubebuilder:validation:Optional
	WindowStartTime *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeParameters `json:"windowStartTime,omitempty" tf:"window_start_time,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeInitParameters struct {

	// (integer, optional)
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeObservation struct {

	// (integer, optional)
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleWindowStartTimeParameters struct {

	// (integer, optional)
	// +kubebuilder:validation:Optional
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	// +kubebuilder:validation:Optional
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type MaintenanceWindowWeekDayBasedScheduleWindowStartTimeInitParameters struct {

	// (integer, optional)
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type MaintenanceWindowWeekDayBasedScheduleWindowStartTimeObservation struct {

	// (integer, optional)
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type MaintenanceWindowWeekDayBasedScheduleWindowStartTimeParameters struct {

	// (integer, optional)
	// +kubebuilder:validation:Optional
	Hours *float64 `json:"hours,omitempty" tf:"hours,omitempty"`

	// (integer, optional)
	// +kubebuilder:validation:Optional
	Minutes *float64 `json:"minutes,omitempty" tf:"minutes,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyInitParameters struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	AccessPolicyType *string `json:"accessPolicyType,omitempty" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyObservation struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	AccessPolicyType *string `json:"accessPolicyType,omitempty" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyParameters struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	// +kubebuilder:validation:Optional
	AccessPolicyType *string `json:"accessPolicyType" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsInitParameters struct {

	// (list of string, optional)
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsObservation struct {

	// (list of string, optional)
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsParameters struct {

	// (list of string, optional)
	// +kubebuilder:validation:Optional
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2AllowedAppsUserAPIScopesInitParameters struct {

	// (list of string, optional)
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2AllowedAppsUserAPIScopesObservation struct {

	// (list of string, optional)
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2AllowedAppsUserAPIScopesParameters struct {

	// (list of string, optional)
	// +kubebuilder:validation:Optional
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2AutomaticClusterUpdateWorkspaceInitParameters struct {

	// (boolean, optional)
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	EnablementDetails *AutomaticClusterUpdateWorkspaceEnablementDetailsInitParameters `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	MaintenanceWindow *AutomaticClusterUpdateWorkspaceMaintenanceWindowInitParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2AutomaticClusterUpdateWorkspaceObservation struct {

	// (boolean, optional)
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	EnablementDetails *AutomaticClusterUpdateWorkspaceEnablementDetailsObservation `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	MaintenanceWindow *AutomaticClusterUpdateWorkspaceMaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2AutomaticClusterUpdateWorkspaceParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	// +kubebuilder:validation:Optional
	EnablementDetails *AutomaticClusterUpdateWorkspaceEnablementDetailsParameters `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	// +kubebuilder:validation:Optional
	MaintenanceWindow *AutomaticClusterUpdateWorkspaceMaintenanceWindowParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2BooleanValInitParameters struct {

	// (boolean, optional)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2BooleanValObservation struct {

	// (boolean, optional)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2BooleanValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2CollaborationPlatformConnectivityInitParameters struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2CollaborationPlatformConnectivityObservation struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2CollaborationPlatformConnectivityParameters struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	// +kubebuilder:validation:Optional
	Connectivity *string `json:"connectivity" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyInitParameters struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	AccessPolicyType *string `json:"accessPolicyType,omitempty" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyObservation struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	AccessPolicyType *string `json:"accessPolicyType,omitempty" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyParameters struct {

	// Possible values are: ALLOW_ALL_DOMAINS, ALLOW_APPROVED_DOMAINS, DENY_ALL_DOMAINS
	// +kubebuilder:validation:Optional
	AccessPolicyType *string `json:"accessPolicyType" tf:"access_policy_type,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsInitParameters struct {

	// (list of string, optional)
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsObservation struct {

	// (list of string, optional)
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsParameters struct {

	// (list of string, optional)
	// +kubebuilder:validation:Optional
	ApprovedDomains []*string `json:"approvedDomains,omitempty" tf:"approved_domains,omitempty"`
}

type WorkspaceSettingV2EffectiveAllowedAppsUserAPIScopesInitParameters struct {

	// (list of string, optional)
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2EffectiveAllowedAppsUserAPIScopesObservation struct {

	// (list of string, optional)
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2EffectiveAllowedAppsUserAPIScopesParameters struct {

	// (list of string, optional)
	// +kubebuilder:validation:Optional
	AllowedScopes []*string `json:"allowedScopes,omitempty" tf:"allowed_scopes,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsInitParameters struct {

	// The feature is force enabled if compliance mode is active
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsObservation struct {

	// The feature is force enabled if compliance mode is active
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsParameters struct {

	// The feature is force enabled if compliance mode is active
	// +kubebuilder:validation:Optional
	ForcedForComplianceMode *bool `json:"forcedForComplianceMode,omitempty" tf:"forced_for_compliance_mode,omitempty"`

	// The feature is unavailable if the corresponding entitlement disabled (see getShieldEntitlementEnable)
	// +kubebuilder:validation:Optional
	UnavailableForDisabledEntitlement *bool `json:"unavailableForDisabledEntitlement,omitempty" tf:"unavailable_for_disabled_entitlement,omitempty"`

	// The feature is unavailable if the customer doesn't have enterprise tier
	// +kubebuilder:validation:Optional
	UnavailableForNonEnterpriseTier *bool `json:"unavailableForNonEnterpriseTier,omitempty" tf:"unavailable_for_non_enterprise_tier,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceInitParameters struct {

	// (boolean, optional)
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	EnablementDetails *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsInitParameters `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	MaintenanceWindow *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowInitParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowInitParameters struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	WeekDayBasedSchedule *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleInitParameters `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowObservation struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	WeekDayBasedSchedule *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleObservation `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowParameters struct {

	// (ClusterAutoRestartMessageMaintenanceWindowWeekDayBasedSchedule, optional)
	// +kubebuilder:validation:Optional
	WeekDayBasedSchedule *EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowWeekDayBasedScheduleParameters `json:"weekDayBasedSchedule,omitempty" tf:"week_day_based_schedule,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceObservation struct {

	// (boolean, optional)
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	EnablementDetails *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsObservation `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	MaintenanceWindow *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	CanToggle *bool `json:"canToggle,omitempty" tf:"can_toggle,omitempty"`

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (ClusterAutoRestartMessageEnablementDetails, optional)
	// +kubebuilder:validation:Optional
	EnablementDetails *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceEnablementDetailsParameters `json:"enablementDetails,omitempty" tf:"enablement_details,omitempty"`

	// (ClusterAutoRestartMessageMaintenanceWindow, optional)
	// +kubebuilder:validation:Optional
	MaintenanceWindow *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceMaintenanceWindowParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	RestartEvenIfNoUpdatesAvailable *bool `json:"restartEvenIfNoUpdatesAvailable,omitempty" tf:"restart_even_if_no_updates_available,omitempty"`
}

type WorkspaceSettingV2EffectiveBooleanValInitParameters struct {

	// (boolean, optional)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveBooleanValObservation struct {

	// (boolean, optional)
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveBooleanValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *bool `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveCollaborationPlatformConnectivityInitParameters struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2EffectiveCollaborationPlatformConnectivityObservation struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2EffectiveCollaborationPlatformConnectivityParameters struct {

	// Possible values are: ALLOW_ALL, ALLOW_SLACK, ALLOW_TEAMS, DENY_ALL
	// +kubebuilder:validation:Optional
	Connectivity *string `json:"connectivity" tf:"connectivity,omitempty"`
}

type WorkspaceSettingV2EffectiveIntegerValInitParameters struct {

	// (boolean, optional)
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveIntegerValObservation struct {

	// (boolean, optional)
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveIntegerValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveOperationalEmailCustomRecipientInitParameters struct {

	// (string, optional)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2EffectiveOperationalEmailCustomRecipientObservation struct {

	// (string, optional)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2EffectiveOperationalEmailCustomRecipientParameters struct {

	// (string, optional)
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2EffectivePersonalComputeInitParameters struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectivePersonalComputeObservation struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectivePersonalComputeParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsInitParameters struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsObservation struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsParameters struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	// +kubebuilder:validation:Optional
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	// +kubebuilder:validation:Optional
	Status *string `json:"status" tf:"status,omitempty"`
}

type WorkspaceSettingV2EffectiveStringValInitParameters struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveStringValObservation struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2EffectiveStringValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2InitParameters struct {

	// Setting value for aibi_dashboard_embedding_access_policy setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_access_policy for final setting value
	AibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyInitParameters `json:"aibiDashboardEmbeddingAccessPolicy,omitempty" tf:"aibi_dashboard_embedding_access_policy,omitempty"`

	// Setting value for aibi_dashboard_embedding_approved_domains setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_approved_domains for final setting value
	AibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsInitParameters `json:"aibiDashboardEmbeddingApprovedDomains,omitempty" tf:"aibi_dashboard_embedding_approved_domains,omitempty"`

	// Setting value for allowed_apps_user_api_scopes setting. This is the setting value set by consumers, check effective_allowed_apps_user_api_scopes for final setting value
	AllowedAppsUserAPIScopes *WorkspaceSettingV2AllowedAppsUserAPIScopesInitParameters `json:"allowedAppsUserApiScopes,omitempty" tf:"allowed_apps_user_api_scopes,omitempty"`

	// Setting value for automatic_cluster_update_workspace setting. This is the setting value set by consumers, check effective_automatic_cluster_update_workspace for final setting value
	AutomaticClusterUpdateWorkspace *WorkspaceSettingV2AutomaticClusterUpdateWorkspaceInitParameters `json:"automaticClusterUpdateWorkspace,omitempty" tf:"automatic_cluster_update_workspace,omitempty"`

	// Setting value for boolean type setting. This is the setting value set by consumers, check effective_boolean_val for final setting value
	BooleanVal *WorkspaceSettingV2BooleanValInitParameters `json:"booleanVal,omitempty" tf:"boolean_val,omitempty"`

	// Setting value for collaboration_platform_connectivity setting. This is the setting value set by consumers, check effective_collaboration_platform_connectivity for final setting value
	CollaborationPlatformConnectivity *WorkspaceSettingV2CollaborationPlatformConnectivityInitParameters `json:"collaborationPlatformConnectivity,omitempty" tf:"collaboration_platform_connectivity,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_access_policy setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_access_policy
	EffectiveAibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyInitParameters `json:"effectiveAibiDashboardEmbeddingAccessPolicy,omitempty" tf:"effective_aibi_dashboard_embedding_access_policy,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_approved_domains setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_approved_domains
	EffectiveAibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsInitParameters `json:"effectiveAibiDashboardEmbeddingApprovedDomains,omitempty" tf:"effective_aibi_dashboard_embedding_approved_domains,omitempty"`

	// Effective setting value for automatic_cluster_update_workspace setting. This is the final effective value of setting. To set a value use automatic_cluster_update_workspace
	EffectiveAutomaticClusterUpdateWorkspace *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceInitParameters `json:"effectiveAutomaticClusterUpdateWorkspace,omitempty" tf:"effective_automatic_cluster_update_workspace,omitempty"`

	// Effective setting value for personal_compute setting. This is the final effective value of setting. To set a value use personal_compute
	EffectivePersonalCompute *WorkspaceSettingV2EffectivePersonalComputeInitParameters `json:"effectivePersonalCompute,omitempty" tf:"effective_personal_compute,omitempty"`

	// Effective setting value for restrict_workspace_admins setting. This is the final effective value of setting. To set a value use restrict_workspace_admins
	EffectiveRestrictWorkspaceAdmins *WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsInitParameters `json:"effectiveRestrictWorkspaceAdmins,omitempty" tf:"effective_restrict_workspace_admins,omitempty"`

	// Setting value for integer type setting. This is the setting value set by consumers, check effective_integer_val for final setting value
	IntegerVal *WorkspaceSettingV2IntegerValInitParameters `json:"integerVal,omitempty" tf:"integer_val,omitempty"`

	// Setting value for operational_email_custom_recipient setting. This is the setting value set by consumers, check effective_operational_email_custom_recipient for final setting value
	OperationalEmailCustomRecipient *WorkspaceSettingV2OperationalEmailCustomRecipientInitParameters `json:"operationalEmailCustomRecipient,omitempty" tf:"operational_email_custom_recipient,omitempty"`

	// Setting value for personal_compute setting. This is the setting value set by consumers, check effective_personal_compute for final setting value
	PersonalCompute *WorkspaceSettingV2PersonalComputeInitParameters `json:"personalCompute,omitempty" tf:"personal_compute,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceSettingV2ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Setting value for restrict_workspace_admins setting. This is the setting value set by consumers, check effective_restrict_workspace_admins for final setting value
	RestrictWorkspaceAdmins *WorkspaceSettingV2RestrictWorkspaceAdminsInitParameters `json:"restrictWorkspaceAdmins,omitempty" tf:"restrict_workspace_admins,omitempty"`

	// Setting value for string type setting. This is the setting value set by consumers, check effective_string_val for final setting value
	StringVal *WorkspaceSettingV2StringValInitParameters `json:"stringVal,omitempty" tf:"string_val,omitempty"`
}

type WorkspaceSettingV2IntegerValInitParameters struct {

	// (boolean, optional)
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2IntegerValObservation struct {

	// (boolean, optional)
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2IntegerValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2Observation struct {

	// Setting value for aibi_dashboard_embedding_access_policy setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_access_policy for final setting value
	AibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyObservation `json:"aibiDashboardEmbeddingAccessPolicy,omitempty" tf:"aibi_dashboard_embedding_access_policy,omitempty"`

	// Setting value for aibi_dashboard_embedding_approved_domains setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_approved_domains for final setting value
	AibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsObservation `json:"aibiDashboardEmbeddingApprovedDomains,omitempty" tf:"aibi_dashboard_embedding_approved_domains,omitempty"`

	// Setting value for allowed_apps_user_api_scopes setting. This is the setting value set by consumers, check effective_allowed_apps_user_api_scopes for final setting value
	AllowedAppsUserAPIScopes *WorkspaceSettingV2AllowedAppsUserAPIScopesObservation `json:"allowedAppsUserApiScopes,omitempty" tf:"allowed_apps_user_api_scopes,omitempty"`

	// Setting value for automatic_cluster_update_workspace setting. This is the setting value set by consumers, check effective_automatic_cluster_update_workspace for final setting value
	AutomaticClusterUpdateWorkspace *WorkspaceSettingV2AutomaticClusterUpdateWorkspaceObservation `json:"automaticClusterUpdateWorkspace,omitempty" tf:"automatic_cluster_update_workspace,omitempty"`

	// Setting value for boolean type setting. This is the setting value set by consumers, check effective_boolean_val for final setting value
	BooleanVal *WorkspaceSettingV2BooleanValObservation `json:"booleanVal,omitempty" tf:"boolean_val,omitempty"`

	// Setting value for collaboration_platform_connectivity setting. This is the setting value set by consumers, check effective_collaboration_platform_connectivity for final setting value
	CollaborationPlatformConnectivity *WorkspaceSettingV2CollaborationPlatformConnectivityObservation `json:"collaborationPlatformConnectivity,omitempty" tf:"collaboration_platform_connectivity,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_access_policy setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_access_policy
	EffectiveAibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyObservation `json:"effectiveAibiDashboardEmbeddingAccessPolicy,omitempty" tf:"effective_aibi_dashboard_embedding_access_policy,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_approved_domains setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_approved_domains
	EffectiveAibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsObservation `json:"effectiveAibiDashboardEmbeddingApprovedDomains,omitempty" tf:"effective_aibi_dashboard_embedding_approved_domains,omitempty"`

	// Effective setting value for allowed_apps_user_api_scopes setting. This is the final effective value of setting. To set a value use allowed_apps_user_api_scopes
	EffectiveAllowedAppsUserAPIScopes *WorkspaceSettingV2EffectiveAllowedAppsUserAPIScopesObservation `json:"effectiveAllowedAppsUserApiScopes,omitempty" tf:"effective_allowed_apps_user_api_scopes,omitempty"`

	// Effective setting value for automatic_cluster_update_workspace setting. This is the final effective value of setting. To set a value use automatic_cluster_update_workspace
	EffectiveAutomaticClusterUpdateWorkspace *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceObservation `json:"effectiveAutomaticClusterUpdateWorkspace,omitempty" tf:"effective_automatic_cluster_update_workspace,omitempty"`

	// Effective setting value for boolean type setting. This is the final effective value of setting. To set a value use boolean_val
	EffectiveBooleanVal *WorkspaceSettingV2EffectiveBooleanValObservation `json:"effectiveBooleanVal,omitempty" tf:"effective_boolean_val,omitempty"`

	// Effective setting value for collaboration_platform_connectivity setting. This is the final effective value of setting. To set a value use collaboration_platform_connectivity
	EffectiveCollaborationPlatformConnectivity *WorkspaceSettingV2EffectiveCollaborationPlatformConnectivityObservation `json:"effectiveCollaborationPlatformConnectivity,omitempty" tf:"effective_collaboration_platform_connectivity,omitempty"`

	// Effective setting value for integer type setting. This is the final effective value of setting. To set a value use integer_val
	EffectiveIntegerVal *WorkspaceSettingV2EffectiveIntegerValObservation `json:"effectiveIntegerVal,omitempty" tf:"effective_integer_val,omitempty"`

	// Effective setting value for operational_email_custom_recipient setting. This is the final effective value of setting. To set a value use operational_email_custom_recipient
	EffectiveOperationalEmailCustomRecipient *WorkspaceSettingV2EffectiveOperationalEmailCustomRecipientObservation `json:"effectiveOperationalEmailCustomRecipient,omitempty" tf:"effective_operational_email_custom_recipient,omitempty"`

	// Effective setting value for personal_compute setting. This is the final effective value of setting. To set a value use personal_compute
	EffectivePersonalCompute *WorkspaceSettingV2EffectivePersonalComputeObservation `json:"effectivePersonalCompute,omitempty" tf:"effective_personal_compute,omitempty"`

	// Effective setting value for restrict_workspace_admins setting. This is the final effective value of setting. To set a value use restrict_workspace_admins
	EffectiveRestrictWorkspaceAdmins *WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsObservation `json:"effectiveRestrictWorkspaceAdmins,omitempty" tf:"effective_restrict_workspace_admins,omitempty"`

	// Effective setting value for string type setting. This is the final effective value of setting. To set a value use string_val
	EffectiveStringVal *WorkspaceSettingV2EffectiveStringValObservation `json:"effectiveStringVal,omitempty" tf:"effective_string_val,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Setting value for integer type setting. This is the setting value set by consumers, check effective_integer_val for final setting value
	IntegerVal *WorkspaceSettingV2IntegerValObservation `json:"integerVal,omitempty" tf:"integer_val,omitempty"`

	// Setting value for operational_email_custom_recipient setting. This is the setting value set by consumers, check effective_operational_email_custom_recipient for final setting value
	OperationalEmailCustomRecipient *WorkspaceSettingV2OperationalEmailCustomRecipientObservation `json:"operationalEmailCustomRecipient,omitempty" tf:"operational_email_custom_recipient,omitempty"`

	// Setting value for personal_compute setting. This is the setting value set by consumers, check effective_personal_compute for final setting value
	PersonalCompute *WorkspaceSettingV2PersonalComputeObservation `json:"personalCompute,omitempty" tf:"personal_compute,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *WorkspaceSettingV2ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Setting value for restrict_workspace_admins setting. This is the setting value set by consumers, check effective_restrict_workspace_admins for final setting value
	RestrictWorkspaceAdmins *WorkspaceSettingV2RestrictWorkspaceAdminsObservation `json:"restrictWorkspaceAdmins,omitempty" tf:"restrict_workspace_admins,omitempty"`

	// Setting value for string type setting. This is the setting value set by consumers, check effective_string_val for final setting value
	StringVal *WorkspaceSettingV2StringValObservation `json:"stringVal,omitempty" tf:"string_val,omitempty"`
}

type WorkspaceSettingV2OperationalEmailCustomRecipientInitParameters struct {

	// (string, optional)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2OperationalEmailCustomRecipientObservation struct {

	// (string, optional)
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2OperationalEmailCustomRecipientParameters struct {

	// (string, optional)
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type WorkspaceSettingV2Parameters struct {

	// Setting value for aibi_dashboard_embedding_access_policy setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_access_policy for final setting value
	// +kubebuilder:validation:Optional
	AibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2AibiDashboardEmbeddingAccessPolicyParameters `json:"aibiDashboardEmbeddingAccessPolicy,omitempty" tf:"aibi_dashboard_embedding_access_policy,omitempty"`

	// Setting value for aibi_dashboard_embedding_approved_domains setting. This is the setting value set by consumers, check effective_aibi_dashboard_embedding_approved_domains for final setting value
	// +kubebuilder:validation:Optional
	AibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2AibiDashboardEmbeddingApprovedDomainsParameters `json:"aibiDashboardEmbeddingApprovedDomains,omitempty" tf:"aibi_dashboard_embedding_approved_domains,omitempty"`

	// Setting value for allowed_apps_user_api_scopes setting. This is the setting value set by consumers, check effective_allowed_apps_user_api_scopes for final setting value
	// +kubebuilder:validation:Optional
	AllowedAppsUserAPIScopes *WorkspaceSettingV2AllowedAppsUserAPIScopesParameters `json:"allowedAppsUserApiScopes,omitempty" tf:"allowed_apps_user_api_scopes,omitempty"`

	// Setting value for automatic_cluster_update_workspace setting. This is the setting value set by consumers, check effective_automatic_cluster_update_workspace for final setting value
	// +kubebuilder:validation:Optional
	AutomaticClusterUpdateWorkspace *WorkspaceSettingV2AutomaticClusterUpdateWorkspaceParameters `json:"automaticClusterUpdateWorkspace,omitempty" tf:"automatic_cluster_update_workspace,omitempty"`

	// Setting value for boolean type setting. This is the setting value set by consumers, check effective_boolean_val for final setting value
	// +kubebuilder:validation:Optional
	BooleanVal *WorkspaceSettingV2BooleanValParameters `json:"booleanVal,omitempty" tf:"boolean_val,omitempty"`

	// Setting value for collaboration_platform_connectivity setting. This is the setting value set by consumers, check effective_collaboration_platform_connectivity for final setting value
	// +kubebuilder:validation:Optional
	CollaborationPlatformConnectivity *WorkspaceSettingV2CollaborationPlatformConnectivityParameters `json:"collaborationPlatformConnectivity,omitempty" tf:"collaboration_platform_connectivity,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_access_policy setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_access_policy
	// +kubebuilder:validation:Optional
	EffectiveAibiDashboardEmbeddingAccessPolicy *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingAccessPolicyParameters `json:"effectiveAibiDashboardEmbeddingAccessPolicy,omitempty" tf:"effective_aibi_dashboard_embedding_access_policy,omitempty"`

	// Effective setting value for aibi_dashboard_embedding_approved_domains setting. This is the final effective value of setting. To set a value use aibi_dashboard_embedding_approved_domains
	// +kubebuilder:validation:Optional
	EffectiveAibiDashboardEmbeddingApprovedDomains *WorkspaceSettingV2EffectiveAibiDashboardEmbeddingApprovedDomainsParameters `json:"effectiveAibiDashboardEmbeddingApprovedDomains,omitempty" tf:"effective_aibi_dashboard_embedding_approved_domains,omitempty"`

	// Effective setting value for automatic_cluster_update_workspace setting. This is the final effective value of setting. To set a value use automatic_cluster_update_workspace
	// +kubebuilder:validation:Optional
	EffectiveAutomaticClusterUpdateWorkspace *WorkspaceSettingV2EffectiveAutomaticClusterUpdateWorkspaceParameters `json:"effectiveAutomaticClusterUpdateWorkspace,omitempty" tf:"effective_automatic_cluster_update_workspace,omitempty"`

	// Effective setting value for personal_compute setting. This is the final effective value of setting. To set a value use personal_compute
	// +kubebuilder:validation:Optional
	EffectivePersonalCompute *WorkspaceSettingV2EffectivePersonalComputeParameters `json:"effectivePersonalCompute,omitempty" tf:"effective_personal_compute,omitempty"`

	// Effective setting value for restrict_workspace_admins setting. This is the final effective value of setting. To set a value use restrict_workspace_admins
	// +kubebuilder:validation:Optional
	EffectiveRestrictWorkspaceAdmins *WorkspaceSettingV2EffectiveRestrictWorkspaceAdminsParameters `json:"effectiveRestrictWorkspaceAdmins,omitempty" tf:"effective_restrict_workspace_admins,omitempty"`

	// Setting value for integer type setting. This is the setting value set by consumers, check effective_integer_val for final setting value
	// +kubebuilder:validation:Optional
	IntegerVal *WorkspaceSettingV2IntegerValParameters `json:"integerVal,omitempty" tf:"integer_val,omitempty"`

	// Setting value for operational_email_custom_recipient setting. This is the setting value set by consumers, check effective_operational_email_custom_recipient for final setting value
	// +kubebuilder:validation:Optional
	OperationalEmailCustomRecipient *WorkspaceSettingV2OperationalEmailCustomRecipientParameters `json:"operationalEmailCustomRecipient,omitempty" tf:"operational_email_custom_recipient,omitempty"`

	// Setting value for personal_compute setting. This is the setting value set by consumers, check effective_personal_compute for final setting value
	// +kubebuilder:validation:Optional
	PersonalCompute *WorkspaceSettingV2PersonalComputeParameters `json:"personalCompute,omitempty" tf:"personal_compute,omitempty"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *WorkspaceSettingV2ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Setting value for restrict_workspace_admins setting. This is the setting value set by consumers, check effective_restrict_workspace_admins for final setting value
	// +kubebuilder:validation:Optional
	RestrictWorkspaceAdmins *WorkspaceSettingV2RestrictWorkspaceAdminsParameters `json:"restrictWorkspaceAdmins,omitempty" tf:"restrict_workspace_admins,omitempty"`

	// Setting value for string type setting. This is the setting value set by consumers, check effective_string_val for final setting value
	// +kubebuilder:validation:Optional
	StringVal *WorkspaceSettingV2StringValParameters `json:"stringVal,omitempty" tf:"string_val,omitempty"`
}

type WorkspaceSettingV2PersonalComputeInitParameters struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2PersonalComputeObservation struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2PersonalComputeParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceSettingV2ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceSettingV2ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type WorkspaceSettingV2RestrictWorkspaceAdminsInitParameters struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type WorkspaceSettingV2RestrictWorkspaceAdminsObservation struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type WorkspaceSettingV2RestrictWorkspaceAdminsParameters struct {

	// When true, workspace admins cannot create governance tags.
	// ALLOW_ALL status does not override this; they are independent
	// +kubebuilder:validation:Optional
	DisableGovTagCreation *bool `json:"disableGovTagCreation,omitempty" tf:"disable_gov_tag_creation,omitempty"`

	// Possible values are: ALLOW_ALL, RESTRICT_TOKENS_AND_JOB_RUN_AS
	// +kubebuilder:validation:Optional
	Status *string `json:"status" tf:"status,omitempty"`
}

type WorkspaceSettingV2StringValInitParameters struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2StringValObservation struct {

	// (boolean, optional)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type WorkspaceSettingV2StringValParameters struct {

	// (boolean, optional)
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// WorkspaceSettingV2Spec defines the desired state of WorkspaceSettingV2
type WorkspaceSettingV2Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceSettingV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceSettingV2InitParameters `json:"initProvider,omitempty"`
}

// WorkspaceSettingV2Status defines the observed state of WorkspaceSettingV2.
type WorkspaceSettingV2Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               WorkspaceSettingV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceSettingV2 is the Schema for the WorkspaceSettingV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,databricks}
type WorkspaceSettingV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkspaceSettingV2Spec   `json:"spec"`
	Status            WorkspaceSettingV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceSettingV2List contains a list of WorkspaceSettingV2s
type WorkspaceSettingV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceSettingV2 `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceSettingV2_Kind             = "WorkspaceSettingV2"
	WorkspaceSettingV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceSettingV2_Kind}.String()
	WorkspaceSettingV2_KindAPIVersion   = WorkspaceSettingV2_Kind + "." + CRDGroupVersion.String()
	WorkspaceSettingV2_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceSettingV2_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceSettingV2{}, &WorkspaceSettingV2List{})
}
