# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: settings.databricks.crossplane.io/v1alpha1
kind: ComplianceSecurityProfileWorkspaceSetting
metadata:
  annotations:
    meta.upbound.io/example-id: settings/v1alpha1/compliancesecurityprofileworkspacesetting
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    complianceSecurityProfileWorkspace:
      - complianceStandards:
          - NONE
        isEnabled: true
