apiVersion: databricks.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  annotations: {}
  name: default
  namespace: upbound-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-secret
      namespace: upbound-system
      key: credentials


# This provider need to have a configuration json payload with the following format:
# For more details, please refer to the provider documentation:
# https://registry.terraform.io/providers/databricks/databricks/1.110.0/docs#argument-reference
#
# Using PAT (Personal Access Token) authentication method:
# {
#   "host": "https://adb-xxxxxxxxxxxxx.42.azuredatabricks.net",
#   "token": "dapiXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-2",
#   "auth_type": "pat"  
# }

# Using AAD (Azure Active Directory) authentication method:
# {
#   "host": "https://adb-xxxxxxxxxxxxx.42.azuredatabricks.net",
#   "azure_client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
#   "azure_client_secret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
#   "azure_tenant_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
#   "auth_type": "azure-client-secret",
#   "account_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# }