apiVersion: databricks.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: dbx-wk-dev-creds
      namespace: crossplane-system
      key: credentials
