# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: workspace.databricks.crossplane.io/v1alpha2
kind: GitCredential
metadata:
  annotations:
    meta.upbound.io/example-id: workspace/v1alpha2/gitcredential
  labels:
    testing.upbound.io/example-name: ado
  name: ado
spec:
  forProvider:
    gitProvider: azureDevOpsServices
    gitUsername: myuser
    personalAccessTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
