apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: MetastoreDataAccess
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/metastoredataaccess
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    awsIamRole:
    - roleArn: ${aws_iam_role.metastore_data_access.arn}
    isDefault: true
    metastoreId: ${databricks_metastore.this.id}
    name: ${aws_iam_role.metastore_data_access.name}

---

apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: Metastore
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/metastoredataaccess
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    forceDestroy: true
    name: primary
    owner: uc admins
    region: us-east-1
    storageRoot: s3://${aws_s3_bucket.metastore.id}/metastore
