apiVersion: compute.databricks.crossplane.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/pipeline
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    cluster:
    - customTags:
        cluster_type: default
      label: default
      numWorkers: 2
    - customTags:
        cluster_type: maintenance
      label: maintenance
      numWorkers: 1
    configuration:
      key1: value1
      key2: value2
    continuous: false
    library:
    - notebook:
      - path: ${databricks_notebook.dlt_demo.id}
    - file:
      - path: ${databricks_repo.dlt_demo.path}/pipeline.sql
    - glob:
      - include: ${databricks_repo.dlt_demo.path}/subfolder/**
    name: Pipeline Name
    notification:
    - alerts:
      - on-update-failure
      - on-update-fatal-failure
      - on-update-success
      - on-flow-failure
      emailRecipients:
      - user@domain.com
      - user1@domain.com
    storage: /test/first-pipeline

---

apiVersion: workspace.databricks.crossplane.io/v1alpha1
kind: Notebook
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/pipeline
  labels:
    testing.upbound.io/example-name: dlt_demo
  name: dlt-demo
spec:
  forProvider: {}

---

apiVersion: workspace.databricks.crossplane.io/v1alpha1
kind: Repo
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/pipeline
  labels:
    testing.upbound.io/example-name: dlt_demo
  name: dlt-demo
spec:
  forProvider: {}
