// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by managedshim. DO NOT EDIT.

package v1beta1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

func (mg *InstanceProfile) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *InstanceProfile) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *InstanceProfile) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *InstanceProfile) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsCredentials) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsCredentials) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsCredentials) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsCredentials) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsCustomerManagedKeys) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsCustomerManagedKeys) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsCustomerManagedKeys) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsCustomerManagedKeys) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsNccBinding) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsNccBinding) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsNccBinding) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsNccBinding) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsNccPrivateEndpointRule) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsNccPrivateEndpointRule) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsNccPrivateEndpointRule) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsNccPrivateEndpointRule) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsNetworkConnectivityConfig) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsNetworkConnectivityConfig) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsNetworkConnectivityConfig) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsNetworkConnectivityConfig) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsNetworks) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsNetworks) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsNetworks) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsNetworks) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsPrivateAccessSettings) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsPrivateAccessSettings) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsPrivateAccessSettings) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsPrivateAccessSettings) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsStorageConfigurations) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsStorageConfigurations) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsStorageConfigurations) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsStorageConfigurations) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsVPCEndpoint) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsVPCEndpoint) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsVPCEndpoint) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsVPCEndpoint) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

func (mg *MwsWorkspaces) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

func (mg *MwsWorkspaces) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

func (mg *MwsWorkspaces) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

func (mg *MwsWorkspaces) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

