apiVersion: compute.databricks.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: shared_autoscaling
  name: shared-autoscaling-test
spec:
  forProvider:
    autoscale:
    - maxWorkers: 2
      minWorkers: 1
    autoterminationMinutes: 20
    nodeTypeId: Standard_D4plds_v6
    sparkVersion: 16.0.x-scala2.12
    
