//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskInitParameters) DeepCopyInto(out *ColumnMaskInitParameters) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.OnColumn != nil {
		in, out := &in.OnColumn, &out.OnColumn
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]UsingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskInitParameters.
func (in *ColumnMaskInitParameters) DeepCopy() *ColumnMaskInitParameters {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskObservation) DeepCopyInto(out *ColumnMaskObservation) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.OnColumn != nil {
		in, out := &in.OnColumn, &out.OnColumn
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]UsingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskObservation.
func (in *ColumnMaskObservation) DeepCopy() *ColumnMaskObservation {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskParameters) DeepCopyInto(out *ColumnMaskParameters) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.OnColumn != nil {
		in, out := &in.OnColumn, &out.OnColumn
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]UsingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskParameters.
func (in *ColumnMaskParameters) DeepCopy() *ColumnMaskParameters {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchColumnsInitParameters) DeepCopyInto(out *MatchColumnsInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchColumnsInitParameters.
func (in *MatchColumnsInitParameters) DeepCopy() *MatchColumnsInitParameters {
	if in == nil {
		return nil
	}
	out := new(MatchColumnsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchColumnsObservation) DeepCopyInto(out *MatchColumnsObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchColumnsObservation.
func (in *MatchColumnsObservation) DeepCopy() *MatchColumnsObservation {
	if in == nil {
		return nil
	}
	out := new(MatchColumnsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchColumnsParameters) DeepCopyInto(out *MatchColumnsParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Condition != nil {
		in, out := &in.Condition, &out.Condition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchColumnsParameters.
func (in *MatchColumnsParameters) DeepCopy() *MatchColumnsParameters {
	if in == nil {
		return nil
	}
	out := new(MatchColumnsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfo) DeepCopyInto(out *PolicyInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfo.
func (in *PolicyInfo) DeepCopy() *PolicyInfo {
	if in == nil {
		return nil
	}
	out := new(PolicyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoInitParameters) DeepCopyInto(out *PolicyInfoInitParameters) {
	*out = *in
	if in.ColumnMask != nil {
		in, out := &in.ColumnMask, &out.ColumnMask
		*out = new(ColumnMaskInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExceptPrincipals != nil {
		in, out := &in.ExceptPrincipals, &out.ExceptPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ForSecurableType != nil {
		in, out := &in.ForSecurableType, &out.ForSecurableType
		*out = new(string)
		**out = **in
	}
	if in.MatchColumns != nil {
		in, out := &in.MatchColumns, &out.MatchColumns
		*out = make([]MatchColumnsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnSecurableFullname != nil {
		in, out := &in.OnSecurableFullname, &out.OnSecurableFullname
		*out = new(string)
		**out = **in
	}
	if in.OnSecurableType != nil {
		in, out := &in.OnSecurableType, &out.OnSecurableType
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RowFilter != nil {
		in, out := &in.RowFilter, &out.RowFilter
		*out = new(RowFilterInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ToPrincipals != nil {
		in, out := &in.ToPrincipals, &out.ToPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WhenCondition != nil {
		in, out := &in.WhenCondition, &out.WhenCondition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoInitParameters.
func (in *PolicyInfoInitParameters) DeepCopy() *PolicyInfoInitParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoList) DeepCopyInto(out *PolicyInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolicyInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoList.
func (in *PolicyInfoList) DeepCopy() *PolicyInfoList {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolicyInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoObservation) DeepCopyInto(out *PolicyInfoObservation) {
	*out = *in
	if in.ColumnMask != nil {
		in, out := &in.ColumnMask, &out.ColumnMask
		*out = new(ColumnMaskObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(float64)
		**out = **in
	}
	if in.CreatedBy != nil {
		in, out := &in.CreatedBy, &out.CreatedBy
		*out = new(string)
		**out = **in
	}
	if in.ExceptPrincipals != nil {
		in, out := &in.ExceptPrincipals, &out.ExceptPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ForSecurableType != nil {
		in, out := &in.ForSecurableType, &out.ForSecurableType
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MatchColumns != nil {
		in, out := &in.MatchColumns, &out.MatchColumns
		*out = make([]MatchColumnsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnSecurableFullname != nil {
		in, out := &in.OnSecurableFullname, &out.OnSecurableFullname
		*out = new(string)
		**out = **in
	}
	if in.OnSecurableType != nil {
		in, out := &in.OnSecurableType, &out.OnSecurableType
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.RowFilter != nil {
		in, out := &in.RowFilter, &out.RowFilter
		*out = new(RowFilterObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ToPrincipals != nil {
		in, out := &in.ToPrincipals, &out.ToPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(float64)
		**out = **in
	}
	if in.UpdatedBy != nil {
		in, out := &in.UpdatedBy, &out.UpdatedBy
		*out = new(string)
		**out = **in
	}
	if in.WhenCondition != nil {
		in, out := &in.WhenCondition, &out.WhenCondition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoObservation.
func (in *PolicyInfoObservation) DeepCopy() *PolicyInfoObservation {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoParameters) DeepCopyInto(out *PolicyInfoParameters) {
	*out = *in
	if in.ColumnMask != nil {
		in, out := &in.ColumnMask, &out.ColumnMask
		*out = new(ColumnMaskParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.ExceptPrincipals != nil {
		in, out := &in.ExceptPrincipals, &out.ExceptPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ForSecurableType != nil {
		in, out := &in.ForSecurableType, &out.ForSecurableType
		*out = new(string)
		**out = **in
	}
	if in.MatchColumns != nil {
		in, out := &in.MatchColumns, &out.MatchColumns
		*out = make([]MatchColumnsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnSecurableFullname != nil {
		in, out := &in.OnSecurableFullname, &out.OnSecurableFullname
		*out = new(string)
		**out = **in
	}
	if in.OnSecurableType != nil {
		in, out := &in.OnSecurableType, &out.OnSecurableType
		*out = new(string)
		**out = **in
	}
	if in.PolicyType != nil {
		in, out := &in.PolicyType, &out.PolicyType
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.RowFilter != nil {
		in, out := &in.RowFilter, &out.RowFilter
		*out = new(RowFilterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ToPrincipals != nil {
		in, out := &in.ToPrincipals, &out.ToPrincipals
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.WhenCondition != nil {
		in, out := &in.WhenCondition, &out.WhenCondition
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoParameters.
func (in *PolicyInfoParameters) DeepCopy() *PolicyInfoParameters {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoSpec) DeepCopyInto(out *PolicyInfoSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoSpec.
func (in *PolicyInfoSpec) DeepCopy() *PolicyInfoSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyInfoStatus) DeepCopyInto(out *PolicyInfoStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyInfoStatus.
func (in *PolicyInfoStatus) DeepCopy() *PolicyInfoStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigInitParameters) DeepCopyInto(out *ProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigInitParameters.
func (in *ProviderConfigInitParameters) DeepCopy() *ProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigObservation) DeepCopyInto(out *ProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigObservation.
func (in *ProviderConfigObservation) DeepCopy() *ProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigParameters) DeepCopyInto(out *ProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigParameters.
func (in *ProviderConfigParameters) DeepCopy() *ProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterInitParameters) DeepCopyInto(out *RowFilterInitParameters) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]RowFilterUsingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterInitParameters.
func (in *RowFilterInitParameters) DeepCopy() *RowFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(RowFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterObservation) DeepCopyInto(out *RowFilterObservation) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]RowFilterUsingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterObservation.
func (in *RowFilterObservation) DeepCopy() *RowFilterObservation {
	if in == nil {
		return nil
	}
	out := new(RowFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterParameters) DeepCopyInto(out *RowFilterParameters) {
	*out = *in
	if in.FunctionName != nil {
		in, out := &in.FunctionName, &out.FunctionName
		*out = new(string)
		**out = **in
	}
	if in.Using != nil {
		in, out := &in.Using, &out.Using
		*out = make([]RowFilterUsingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterParameters.
func (in *RowFilterParameters) DeepCopy() *RowFilterParameters {
	if in == nil {
		return nil
	}
	out := new(RowFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterUsingInitParameters) DeepCopyInto(out *RowFilterUsingInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterUsingInitParameters.
func (in *RowFilterUsingInitParameters) DeepCopy() *RowFilterUsingInitParameters {
	if in == nil {
		return nil
	}
	out := new(RowFilterUsingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterUsingObservation) DeepCopyInto(out *RowFilterUsingObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterUsingObservation.
func (in *RowFilterUsingObservation) DeepCopy() *RowFilterUsingObservation {
	if in == nil {
		return nil
	}
	out := new(RowFilterUsingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilterUsingParameters) DeepCopyInto(out *RowFilterUsingParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilterUsingParameters.
func (in *RowFilterUsingParameters) DeepCopy() *RowFilterUsingParameters {
	if in == nil {
		return nil
	}
	out := new(RowFilterUsingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsingInitParameters) DeepCopyInto(out *UsingInitParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsingInitParameters.
func (in *UsingInitParameters) DeepCopy() *UsingInitParameters {
	if in == nil {
		return nil
	}
	out := new(UsingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsingObservation) DeepCopyInto(out *UsingObservation) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsingObservation.
func (in *UsingObservation) DeepCopy() *UsingObservation {
	if in == nil {
		return nil
	}
	out := new(UsingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsingParameters) DeepCopyInto(out *UsingParameters) {
	*out = *in
	if in.Alias != nil {
		in, out := &in.Alias, &out.Alias
		*out = new(string)
		**out = **in
	}
	if in.Constant != nil {
		in, out := &in.Constant, &out.Constant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsingParameters.
func (in *UsingParameters) DeepCopy() *UsingParameters {
	if in == nil {
		return nil
	}
	out := new(UsingParameters)
	in.DeepCopyInto(out)
	return out
}
