# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: unity.databricks.m.crossplane.io/v1alpha2
kind: PolicyInfo
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha2/policyinfo
  labels:
    testing.upbound.io/example-name: pii_row_filter
  name: pii-row-filter
  namespace: upbound-system
spec:
  forProvider:
    forSecurableType: TABLE
    matchColumns:
    - alias: pii_col
      condition: hasTag('pii')
    onSecurableFullname: main
    onSecurableType: CATALOG
    policyType: POLICY_TYPE_ROW_FILTER
    rowFilter:
      functionName: main.filters.mask_pii_rows
      using:
      - alias: pii_col
    toPrincipals:
    - account users
    whenCondition: hasTag('pii')
