# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: workspace.databricks.m.crossplane.io/v1beta1
kind: WorkspaceFile
metadata:
  annotations:
    meta.upbound.io/example-id: workspace/v1beta1/workspacefile
  labels:
    testing.upbound.io/example-name: module
  name: module
  namespace: upbound-system
spec:
  forProvider:
    path: ${data.databricks_current_user.me.home}/AA/BB/CC
    source: ${path.module}/module.py
