# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: storage.databricks.crossplane.io/v1alpha2
kind: DbfsFile
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha2/dbfsfile
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    path: /tmp/main.tf
    source: ${path.module}/main.tf
