apiVersion: workspace.databricks.crossplane.io/v1alpha1
kind: WorkspaceConf
metadata:
  annotations:
    meta.upbound.io/example-id: workspace/v1alpha1/workspaceconf
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    customConfig:
      enableIpAccessLists: true
