apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: CatalogWorkspaceBinding
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/catalogworkspacebinding
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    securableName: sandbox
    workspaceId: ${databricks_mws_workspaces.other.workspace_id}

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/catalogworkspacebinding
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    isolationMode: ISOLATED
    name: sandbox
