apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/schema
  labels:
    testing.upbound.io/example-name: things
  name: things
spec:
  forProvider:
    catalogName: ${databricks_catalog.sandbox.id}
    comment: this database is managed by terraform
    name: things
    properties:
      kind: various

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/schema
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    comment: this catalog is managed by terraform
    name: sandbox
    properties:
      purpose: testing
