apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: SQLTable
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: sql-table-test
  name: sql-table-test
spec:
  forProvider:
    catalogName: ${data.databricks_catalog}
    column:
    - name: id
      type: int
    - comment: name of thing
      name: name
      type: string
    comment: this table is managed by crossplane
    name: quickstart_table
    warehouseIdRef: sql-endpoint-test
    schemaName: test
    tableType: MANAGED

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    comment: this catalog is managed by terraform
    name: sandbox
    properties:
      purpose: testing

---

apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/sqltable
  labels:
    testing.upbound.io/example-name: things
  name: things
spec:
  forProvider:
    catalogName: ${databricks_catalog.sandbox.id}
    comment: this database is managed by terraform
    name: things
    properties:
      kind: various
