# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: unity.databricks.crossplane.io/v1alpha2
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha2/schema
  labels:
    testing.upbound.io/example-name: things
  name: things
spec:
  forProvider:
    catalogNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sandbox
    comment: this database is managed by terraform
    name: things
    properties:
      kind: various

---

apiVersion: unity.databricks.crossplane.io/v1alpha2
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha2/schema
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    comment: this catalog is managed by terraform
    name: sandbox
    properties:
      purpose: testing
