# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: deployment.databricks.crossplane.io/v1beta1
kind: MwsNccBinding
metadata:
  annotations:
    meta.upbound.io/example-id: deployment/v1beta1/mwsnccbinding
  labels:
    testing.upbound.io/example-name: ncc_binding
  name: ncc-binding
spec:
  forProvider:
    networkConnectivityConfigIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ncc
    provider: ${databricks.account}
    workspaceId: ${var.databricks_workspace_id}

---

apiVersion: deployment.databricks.crossplane.io/v1beta1
kind: MwsNetworkConnectivityConfig
metadata:
  annotations:
    meta.upbound.io/example-id: deployment/v1beta1/mwsnccbinding
  labels:
    testing.upbound.io/example-name: ncc
  name: ncc
spec:
  forProvider:
    name: ncc-for-${var.prefix}
    provider: ${databricks.account}
    region: ${var.region}
