// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: CC0-1.0

package cluster

import (
	"github.com/glalanne/provider-databricks/config/cluster/access_control_rule_set"
	"github.com/glalanne/provider-databricks/config/cluster/account_federation_policy"
	"github.com/glalanne/provider-databricks/config/cluster/alert"
	"github.com/glalanne/provider-databricks/config/cluster/app"
	"github.com/glalanne/provider-databricks/config/cluster/artifact_allowlist"
	"github.com/glalanne/provider-databricks/config/cluster/budget"
	"github.com/glalanne/provider-databricks/config/cluster/catalog"
	"github.com/glalanne/provider-databricks/config/cluster/catalog_workspace_binding"
	"github.com/glalanne/provider-databricks/config/cluster/cluster"
	"github.com/glalanne/provider-databricks/config/cluster/cluster_policy"
	"github.com/glalanne/provider-databricks/config/cluster/compliance_security_profile_workspace_setting"
	"github.com/glalanne/provider-databricks/config/cluster/connection"
	"github.com/glalanne/provider-databricks/config/cluster/credential"
	"github.com/glalanne/provider-databricks/config/cluster/custom_app_integration"
	"github.com/glalanne/provider-databricks/config/cluster/dashboard"
	"github.com/glalanne/provider-databricks/config/cluster/dbfs_file"
	"github.com/glalanne/provider-databricks/config/cluster/default_namespace_setting"
	"github.com/glalanne/provider-databricks/config/cluster/directory"
	"github.com/glalanne/provider-databricks/config/cluster/enhanced_security_monitoring_workspace_setting"
	"github.com/glalanne/provider-databricks/config/cluster/entitlements"
	"github.com/glalanne/provider-databricks/config/cluster/external_location"
	"github.com/glalanne/provider-databricks/config/cluster/file"
	"github.com/glalanne/provider-databricks/config/cluster/git_credential"
	"github.com/glalanne/provider-databricks/config/cluster/global_init_script"
	"github.com/glalanne/provider-databricks/config/cluster/grant"
	"github.com/glalanne/provider-databricks/config/cluster/grants"
	"github.com/glalanne/provider-databricks/config/cluster/group"
	"github.com/glalanne/provider-databricks/config/cluster/group_instance_profile"
	"github.com/glalanne/provider-databricks/config/cluster/group_member"
	"github.com/glalanne/provider-databricks/config/cluster/group_role"
	"github.com/glalanne/provider-databricks/config/cluster/instance_pool"
	"github.com/glalanne/provider-databricks/config/cluster/instance_profile"
	"github.com/glalanne/provider-databricks/config/cluster/ip_access_list"
	"github.com/glalanne/provider-databricks/config/cluster/job"
	"github.com/glalanne/provider-databricks/config/cluster/lakehouse_monitor"
	"github.com/glalanne/provider-databricks/config/cluster/library"
	"github.com/glalanne/provider-databricks/config/cluster/metastore"
	"github.com/glalanne/provider-databricks/config/cluster/metastore_assignment"
	"github.com/glalanne/provider-databricks/config/cluster/metastore_data_access"
	"github.com/glalanne/provider-databricks/config/cluster/mlflow_experiment"
	"github.com/glalanne/provider-databricks/config/cluster/mlflow_model"
	"github.com/glalanne/provider-databricks/config/cluster/mlflow_webhook"
	"github.com/glalanne/provider-databricks/config/cluster/model_serving"
	"github.com/glalanne/provider-databricks/config/cluster/mount"
	"github.com/glalanne/provider-databricks/config/cluster/mws_credentials"
	"github.com/glalanne/provider-databricks/config/cluster/mws_customer_managed_keys"
	"github.com/glalanne/provider-databricks/config/cluster/mws_log_delivery"
	"github.com/glalanne/provider-databricks/config/cluster/mws_ncc_binding"
	"github.com/glalanne/provider-databricks/config/cluster/mws_ncc_private_endpoint_rule"
	"github.com/glalanne/provider-databricks/config/cluster/mws_network_connectivity_config"
	"github.com/glalanne/provider-databricks/config/cluster/mws_networks"
	"github.com/glalanne/provider-databricks/config/cluster/mws_permission_assignment"
	"github.com/glalanne/provider-databricks/config/cluster/mws_private_access_settings"
	"github.com/glalanne/provider-databricks/config/cluster/mws_storage_configurations"
	"github.com/glalanne/provider-databricks/config/cluster/mws_vpc_endpoint"
	"github.com/glalanne/provider-databricks/config/cluster/mws_workspaces"
	"github.com/glalanne/provider-databricks/config/cluster/notebook"
	"github.com/glalanne/provider-databricks/config/cluster/notification_destination"
	"github.com/glalanne/provider-databricks/config/cluster/obo_token"
	"github.com/glalanne/provider-databricks/config/cluster/online_table"
	"github.com/glalanne/provider-databricks/config/cluster/permission_assignment"
	"github.com/glalanne/provider-databricks/config/cluster/permissions"
	"github.com/glalanne/provider-databricks/config/cluster/pipeline"
	"github.com/glalanne/provider-databricks/config/cluster/provider"
	"github.com/glalanne/provider-databricks/config/cluster/quality_monitor"
	"github.com/glalanne/provider-databricks/config/cluster/query"
	"github.com/glalanne/provider-databricks/config/cluster/recipient"
	"github.com/glalanne/provider-databricks/config/cluster/registered_model"
	"github.com/glalanne/provider-databricks/config/cluster/repo"
	"github.com/glalanne/provider-databricks/config/cluster/restrict_workspace_admins_setting"
	"github.com/glalanne/provider-databricks/config/cluster/schema"
	"github.com/glalanne/provider-databricks/config/cluster/secret"
	"github.com/glalanne/provider-databricks/config/cluster/secret_acl"
	"github.com/glalanne/provider-databricks/config/cluster/secret_scope"
	"github.com/glalanne/provider-databricks/config/cluster/service_principal"
	"github.com/glalanne/provider-databricks/config/cluster/service_principal_federation_policy"
	"github.com/glalanne/provider-databricks/config/cluster/service_principal_role"
	"github.com/glalanne/provider-databricks/config/cluster/service_principal_secret"
	"github.com/glalanne/provider-databricks/config/cluster/share"
	"github.com/glalanne/provider-databricks/config/cluster/sql_alert"
	"github.com/glalanne/provider-databricks/config/cluster/sql_dashboard"
	"github.com/glalanne/provider-databricks/config/cluster/sql_endpoint"
	"github.com/glalanne/provider-databricks/config/cluster/sql_global_config"
	"github.com/glalanne/provider-databricks/config/cluster/sql_permissions"
	"github.com/glalanne/provider-databricks/config/cluster/sql_query"
	"github.com/glalanne/provider-databricks/config/cluster/sql_table"
	"github.com/glalanne/provider-databricks/config/cluster/sql_visualization"
	"github.com/glalanne/provider-databricks/config/cluster/sql_widget"
	"github.com/glalanne/provider-databricks/config/cluster/storage_credential"
	"github.com/glalanne/provider-databricks/config/cluster/system_schema"
	"github.com/glalanne/provider-databricks/config/cluster/token"
	"github.com/glalanne/provider-databricks/config/cluster/user"
	"github.com/glalanne/provider-databricks/config/cluster/user_instance_profile"
	"github.com/glalanne/provider-databricks/config/cluster/user_role"
	"github.com/glalanne/provider-databricks/config/cluster/vector_search_endpoint"
	"github.com/glalanne/provider-databricks/config/cluster/vector_search_index"
	"github.com/glalanne/provider-databricks/config/cluster/volume"
	"github.com/glalanne/provider-databricks/config/cluster/workspace_binding"
	"github.com/glalanne/provider-databricks/config/cluster/workspace_conf"
	"github.com/glalanne/provider-databricks/config/cluster/workspace_file"
)

func init() {
	ProviderConfiguration.AddConfig(cluster.Configure)
	ProviderConfiguration.AddConfig(cluster_policy.Configure)
	ProviderConfiguration.AddConfig(credential.Configure)
	ProviderConfiguration.AddConfig(token.Configure)
	ProviderConfiguration.AddConfig(secret.Configure)
	ProviderConfiguration.AddConfig(secret_scope.Configure)
	ProviderConfiguration.AddConfig(notebook.Configure)
	ProviderConfiguration.AddConfig(job.Configure)
	ProviderConfiguration.AddConfig(instance_pool.Configure)
	ProviderConfiguration.AddConfig(permissions.Configure)
	ProviderConfiguration.AddConfig(sql_endpoint.Configure)
	ProviderConfiguration.AddConfig(entitlements.Configure)
	ProviderConfiguration.AddConfig(group.Configure)
	ProviderConfiguration.AddConfig(group_member.Configure)
	ProviderConfiguration.AddConfig(group_role.Configure)
	ProviderConfiguration.AddConfig(ip_access_list.Configure)
	ProviderConfiguration.AddConfig(permission_assignment.Configure)
	ProviderConfiguration.AddConfig(service_principal.Configure)
	ProviderConfiguration.AddConfig(service_principal_role.Configure)
	ProviderConfiguration.AddConfig(sql_permissions.Configure)
	ProviderConfiguration.AddConfig(grants.Configure)
	ProviderConfiguration.AddConfig(pipeline.Configure)
	ProviderConfiguration.AddConfig(alert.Configure)
	ProviderConfiguration.AddConfig(query.Configure)
	ProviderConfiguration.AddConfig(sql_alert.Configure)
	ProviderConfiguration.AddConfig(sql_dashboard.Configure)
	ProviderConfiguration.AddConfig(sql_global_config.Configure)
	ProviderConfiguration.AddConfig(sql_query.Configure)
	ProviderConfiguration.AddConfig(sql_table.Configure)
	ProviderConfiguration.AddConfig(budget.Configure)
	ProviderConfiguration.AddConfig(git_credential.Configure)
	ProviderConfiguration.AddConfig(catalog.Configure)
	ProviderConfiguration.AddConfig(connection.Configure)
	ProviderConfiguration.AddConfig(external_location.Configure)
	ProviderConfiguration.AddConfig(schema.Configure)
	ProviderConfiguration.AddConfig(library.Configure)
	ProviderConfiguration.AddConfig(sql_visualization.Configure)
	ProviderConfiguration.AddConfig(sql_widget.Configure)
	ProviderConfiguration.AddConfig(provider.Configure)
	ProviderConfiguration.AddConfig(mlflow_experiment.Configure)
	ProviderConfiguration.AddConfig(mlflow_model.Configure)
	ProviderConfiguration.AddConfig(mlflow_webhook.Configure)
	ProviderConfiguration.AddConfig(model_serving.Configure)
	ProviderConfiguration.AddConfig(access_control_rule_set.Configure)
	ProviderConfiguration.AddConfig(artifact_allowlist.Configure)
	ProviderConfiguration.AddConfig(catalog_workspace_binding.Configure)
	ProviderConfiguration.AddConfig(compliance_security_profile_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(custom_app_integration.Configure)
	ProviderConfiguration.AddConfig(dashboard.Configure)
	ProviderConfiguration.AddConfig(dbfs_file.Configure)
	ProviderConfiguration.AddConfig(default_namespace_setting.Configure)
	ProviderConfiguration.AddConfig(directory.Configure)
	ProviderConfiguration.AddConfig(enhanced_security_monitoring_workspace_setting.Configure)
	ProviderConfiguration.AddConfig(file.Configure)
	ProviderConfiguration.AddConfig(global_init_script.Configure)
	ProviderConfiguration.AddConfig(grant.Configure)
	ProviderConfiguration.AddConfig(group_instance_profile.Configure)
	ProviderConfiguration.AddConfig(instance_profile.Configure)
	ProviderConfiguration.AddConfig(lakehouse_monitor.Configure)
	ProviderConfiguration.AddConfig(metastore.Configure)
	ProviderConfiguration.AddConfig(metastore_assignment.Configure)
	ProviderConfiguration.AddConfig(metastore_data_access.Configure)
	ProviderConfiguration.AddConfig(mount.Configure)
	ProviderConfiguration.AddConfig(mws_credentials.Configure)
	ProviderConfiguration.AddConfig(mws_customer_managed_keys.Configure)
	ProviderConfiguration.AddConfig(mws_log_delivery.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_binding.Configure)
	ProviderConfiguration.AddConfig(mws_ncc_private_endpoint_rule.Configure)
	ProviderConfiguration.AddConfig(mws_network_connectivity_config.Configure)
	ProviderConfiguration.AddConfig(mws_networks.Configure)
	ProviderConfiguration.AddConfig(mws_permission_assignment.Configure)
	ProviderConfiguration.AddConfig(mws_private_access_settings.Configure)
	ProviderConfiguration.AddConfig(mws_storage_configurations.Configure)
	ProviderConfiguration.AddConfig(mws_vpc_endpoint.Configure)
	ProviderConfiguration.AddConfig(mws_workspaces.Configure)
	ProviderConfiguration.AddConfig(notification_destination.Configure)
	ProviderConfiguration.AddConfig(obo_token.Configure)
	ProviderConfiguration.AddConfig(online_table.Configure)
	ProviderConfiguration.AddConfig(quality_monitor.Configure)
	ProviderConfiguration.AddConfig(recipient.Configure)
	ProviderConfiguration.AddConfig(registered_model.Configure)
	ProviderConfiguration.AddConfig(repo.Configure)
	ProviderConfiguration.AddConfig(restrict_workspace_admins_setting.Configure)
	ProviderConfiguration.AddConfig(secret_acl.Configure)
	ProviderConfiguration.AddConfig(service_principal_secret.Configure)
	ProviderConfiguration.AddConfig(share.Configure)
	ProviderConfiguration.AddConfig(storage_credential.Configure)
	ProviderConfiguration.AddConfig(system_schema.Configure)
	ProviderConfiguration.AddConfig(user.Configure)
	ProviderConfiguration.AddConfig(user_instance_profile.Configure)
	ProviderConfiguration.AddConfig(user_role.Configure)
	ProviderConfiguration.AddConfig(vector_search_endpoint.Configure)
	ProviderConfiguration.AddConfig(vector_search_index.Configure)
	ProviderConfiguration.AddConfig(volume.Configure)
	ProviderConfiguration.AddConfig(workspace_binding.Configure)
	ProviderConfiguration.AddConfig(workspace_conf.Configure)
	ProviderConfiguration.AddConfig(workspace_file.Configure)
	ProviderConfiguration.AddConfig(account_federation_policy.Configure)
	ProviderConfiguration.AddConfig(service_principal_federation_policy.Configure)
	ProviderConfiguration.AddConfig(app.Configure)
}
