# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: workspace.databricks.m.crossplane.io/v1alpha2
kind: Notebook
metadata:
  annotations:
    meta.upbound.io/example-id: workspace/v1alpha2/notebook
  labels:
    testing.upbound.io/example-name: ddl
  name: ddl
  namespace: upbound-system
spec:
  forProvider:
    path: ${data.databricks_current_user.me.home}/AA/BB/CC
    source: ${path.module}/DDLgen.py
