apiVersion: mlflow.databricks.crossplane.io/v1alpha1
kind: MlflowExperiment
metadata:
  annotations:
    meta.upbound.io/example-id: mlflow/v1alpha1/mlflowexperiment
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    artifactLocation: dbfs:/tmp/my-experiment
    name: ${data.databricks_current_user.me.home}/Sample
    tags:
    - key: key1
      value: value1
    - key: key2
      value: value2
