// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PostgresBranchInitParameters struct {

	// The part of the name, chosen by the user when the resource was created
	BranchID *string `json:"branchId,omitempty" tf:"branch_id,omitempty"`

	// The project containing this branch (API resource hierarchy).
	// Format: projects/{project_id}
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/postgres/v1beta1.PostgresProject
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Reference to a PostgresProject in postgres to populate parent.
	// +kubebuilder:validation:Optional
	ParentRef *v2.Reference `json:"parentRef,omitempty" tf:"-"`

	// Selector for a PostgresProject in postgres to populate parent.
	// +kubebuilder:validation:Optional
	ParentSelector *v2.Selector `json:"parentSelector,omitempty" tf:"-"`

	// Configure the provider for management through account provider.
	ProviderConfig *ProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// If true, permanently delete the branch; if false, soft delete
	PurgeOnDelete *bool `json:"purgeOnDelete,omitempty" tf:"purge_on_delete,omitempty"`

	// If true, update the branch if it already exists instead of returning an error
	ReplaceExisting *bool `json:"replaceExisting,omitempty" tf:"replace_existing,omitempty"`

	// The spec contains the branch configuration
	Spec *SpecInitParameters `json:"spec,omitempty" tf:"spec,omitempty"`
}

type PostgresBranchObservation struct {

	// The part of the name, chosen by the user when the resource was created
	BranchID *string `json:"branchId,omitempty" tf:"branch_id,omitempty"`

	// A timestamp indicating when the branch was created
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The project containing this branch (API resource hierarchy).
	// Format: projects/{project_id}
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Configure the provider for management through account provider.
	ProviderConfig *ProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// If true, permanently delete the branch; if false, soft delete
	PurgeOnDelete *bool `json:"purgeOnDelete,omitempty" tf:"purge_on_delete,omitempty"`

	// If true, update the branch if it already exists instead of returning an error
	ReplaceExisting *bool `json:"replaceExisting,omitempty" tf:"replace_existing,omitempty"`

	// The spec contains the branch configuration
	Spec *SpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// The current status of a Branch
	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// System-generated unique ID for the branch
	UID *string `json:"uid,omitempty" tf:"uid,omitempty"`

	// A timestamp indicating when the branch was last updated
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type PostgresBranchParameters struct {

	// The part of the name, chosen by the user when the resource was created
	// +kubebuilder:validation:Optional
	BranchID *string `json:"branchId,omitempty" tf:"branch_id,omitempty"`

	// The project containing this branch (API resource hierarchy).
	// Format: projects/{project_id}
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/postgres/v1beta1.PostgresProject
	// +kubebuilder:validation:Optional
	Parent *string `json:"parent,omitempty" tf:"parent,omitempty"`

	// Reference to a PostgresProject in postgres to populate parent.
	// +kubebuilder:validation:Optional
	ParentRef *v2.Reference `json:"parentRef,omitempty" tf:"-"`

	// Selector for a PostgresProject in postgres to populate parent.
	// +kubebuilder:validation:Optional
	ParentSelector *v2.Selector `json:"parentSelector,omitempty" tf:"-"`

	// Configure the provider for management through account provider.
	// +kubebuilder:validation:Optional
	ProviderConfig *ProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// If true, permanently delete the branch; if false, soft delete
	// +kubebuilder:validation:Optional
	PurgeOnDelete *bool `json:"purgeOnDelete,omitempty" tf:"purge_on_delete,omitempty"`

	// If true, update the branch if it already exists instead of returning an error
	// +kubebuilder:validation:Optional
	ReplaceExisting *bool `json:"replaceExisting,omitempty" tf:"replace_existing,omitempty"`

	// The spec contains the branch configuration
	// +kubebuilder:validation:Optional
	Spec *SpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`
}

type ProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type SpecInitParameters struct {

	// Absolute expiration timestamp. When set, the branch will expire at this time.
	// Mutually exclusive with ttl and no_expiry. When updating, use spec.expiration in the update_mask
	ExpireTime *string `json:"expireTime,omitempty" tf:"expire_time,omitempty"`

	// When set to true, protects the branch from deletion and reset. Associated compute endpoints and the project cannot be deleted while the branch is protected
	IsProtected *bool `json:"isProtected,omitempty" tf:"is_protected,omitempty"`

	// Explicitly disable expiration. When set to true, the branch will not expire.
	// If set to false, the request is invalid; provide either ttl or expire_time instead.
	// Mutually exclusive with expire_time and ttl. When updating, use spec.expiration in the update_mask
	NoExpiry *bool `json:"noExpiry,omitempty" tf:"no_expiry,omitempty"`

	// The name of the source branch from which this branch was created (data lineage for point-in-time recovery).
	// If not specified, defaults to the project's default branch.
	// Format: projects/{project_id}/branches/{branch_id}
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The Log Sequence Number (LSN) on the source branch from which this branch was created
	SourceBranchLsn *string `json:"sourceBranchLsn,omitempty" tf:"source_branch_lsn,omitempty"`

	// The point in time on the source branch from which this branch was created
	SourceBranchTime *string `json:"sourceBranchTime,omitempty" tf:"source_branch_time,omitempty"`

	// Relative time-to-live duration. When set, the branch will expire at creation_time + ttl.
	// Mutually exclusive with expire_time and no_expiry. When updating, use spec.expiration in the update_mask
	TTL *string `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type SpecObservation struct {

	// Absolute expiration timestamp. When set, the branch will expire at this time.
	// Mutually exclusive with ttl and no_expiry. When updating, use spec.expiration in the update_mask
	ExpireTime *string `json:"expireTime,omitempty" tf:"expire_time,omitempty"`

	// When set to true, protects the branch from deletion and reset. Associated compute endpoints and the project cannot be deleted while the branch is protected
	IsProtected *bool `json:"isProtected,omitempty" tf:"is_protected,omitempty"`

	// Explicitly disable expiration. When set to true, the branch will not expire.
	// If set to false, the request is invalid; provide either ttl or expire_time instead.
	// Mutually exclusive with expire_time and ttl. When updating, use spec.expiration in the update_mask
	NoExpiry *bool `json:"noExpiry,omitempty" tf:"no_expiry,omitempty"`

	// The name of the source branch from which this branch was created (data lineage for point-in-time recovery).
	// If not specified, defaults to the project's default branch.
	// Format: projects/{project_id}/branches/{branch_id}
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The Log Sequence Number (LSN) on the source branch from which this branch was created
	SourceBranchLsn *string `json:"sourceBranchLsn,omitempty" tf:"source_branch_lsn,omitempty"`

	// The point in time on the source branch from which this branch was created
	SourceBranchTime *string `json:"sourceBranchTime,omitempty" tf:"source_branch_time,omitempty"`

	// Relative time-to-live duration. When set, the branch will expire at creation_time + ttl.
	// Mutually exclusive with expire_time and no_expiry. When updating, use spec.expiration in the update_mask
	TTL *string `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type SpecParameters struct {

	// Absolute expiration timestamp. When set, the branch will expire at this time.
	// Mutually exclusive with ttl and no_expiry. When updating, use spec.expiration in the update_mask
	// +kubebuilder:validation:Optional
	ExpireTime *string `json:"expireTime,omitempty" tf:"expire_time,omitempty"`

	// When set to true, protects the branch from deletion and reset. Associated compute endpoints and the project cannot be deleted while the branch is protected
	// +kubebuilder:validation:Optional
	IsProtected *bool `json:"isProtected,omitempty" tf:"is_protected,omitempty"`

	// Explicitly disable expiration. When set to true, the branch will not expire.
	// If set to false, the request is invalid; provide either ttl or expire_time instead.
	// Mutually exclusive with expire_time and ttl. When updating, use spec.expiration in the update_mask
	// +kubebuilder:validation:Optional
	NoExpiry *bool `json:"noExpiry,omitempty" tf:"no_expiry,omitempty"`

	// The name of the source branch from which this branch was created (data lineage for point-in-time recovery).
	// If not specified, defaults to the project's default branch.
	// Format: projects/{project_id}/branches/{branch_id}
	// +kubebuilder:validation:Optional
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The Log Sequence Number (LSN) on the source branch from which this branch was created
	// +kubebuilder:validation:Optional
	SourceBranchLsn *string `json:"sourceBranchLsn,omitempty" tf:"source_branch_lsn,omitempty"`

	// The point in time on the source branch from which this branch was created
	// +kubebuilder:validation:Optional
	SourceBranchTime *string `json:"sourceBranchTime,omitempty" tf:"source_branch_time,omitempty"`

	// Relative time-to-live duration. When set, the branch will expire at creation_time + ttl.
	// Mutually exclusive with expire_time and no_expiry. When updating, use spec.expiration in the update_mask
	// +kubebuilder:validation:Optional
	TTL *string `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// The part of the name, chosen by the user when the resource was created
	BranchID *string `json:"branchId,omitempty" tf:"branch_id,omitempty"`

	// The branch's state, indicating if it is initializing, ready for use, or archived. Possible values are: ARCHIVED, DELETED, IMPORTING, INIT, READY, RESETTING
	CurrentState *string `json:"currentState,omitempty" tf:"current_state,omitempty"`

	// Whether the branch is the project's default branch
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// A timestamp indicating when the branch was deleted.
	// Empty if the branch is not deleted
	DeleteTime *string `json:"deleteTime,omitempty" tf:"delete_time,omitempty"`

	// Absolute expiration timestamp. When set, the branch will expire at this time.
	// Mutually exclusive with ttl and no_expiry. When updating, use spec.expiration in the update_mask
	ExpireTime *string `json:"expireTime,omitempty" tf:"expire_time,omitempty"`

	// When set to true, protects the branch from deletion and reset. Associated compute endpoints and the project cannot be deleted while the branch is protected
	IsProtected *bool `json:"isProtected,omitempty" tf:"is_protected,omitempty"`

	// The logical size of the branch
	LogicalSizeBytes *float64 `json:"logicalSizeBytes,omitempty" tf:"logical_size_bytes,omitempty"`

	// The pending state of the branch, if a state transition is in progress. Possible values are: ARCHIVED, DELETED, IMPORTING, INIT, READY, RESETTING
	PendingState *string `json:"pendingState,omitempty" tf:"pending_state,omitempty"`

	// A timestamp indicating when the branch is scheduled to be purged.
	// Empty if the branch is not deleted, otherwise set to a timestamp in the future
	PurgeTime *string `json:"purgeTime,omitempty" tf:"purge_time,omitempty"`

	// The name of the source branch from which this branch was created (data lineage for point-in-time recovery).
	// If not specified, defaults to the project's default branch.
	// Format: projects/{project_id}/branches/{branch_id}
	SourceBranch *string `json:"sourceBranch,omitempty" tf:"source_branch,omitempty"`

	// The Log Sequence Number (LSN) on the source branch from which this branch was created
	SourceBranchLsn *string `json:"sourceBranchLsn,omitempty" tf:"source_branch_lsn,omitempty"`

	// The point in time on the source branch from which this branch was created
	SourceBranchTime *string `json:"sourceBranchTime,omitempty" tf:"source_branch_time,omitempty"`

	// A timestamp indicating when the current_state began
	StateChangeTime *string `json:"stateChangeTime,omitempty" tf:"state_change_time,omitempty"`
}

type StatusParameters struct {
}

// PostgresBranchSpec defines the desired state of PostgresBranch
type PostgresBranchSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   PostgresBranchParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PostgresBranchInitParameters `json:"initProvider,omitempty"`
}

// PostgresBranchStatus defines the observed state of PostgresBranch.
type PostgresBranchStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PostgresBranchObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PostgresBranch is the Schema for the PostgresBranchs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type PostgresBranch struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.branchId) || (has(self.initProvider) && has(self.initProvider.branchId))",message="spec.forProvider.branchId is a required parameter"
	Spec   PostgresBranchSpec   `json:"spec"`
	Status PostgresBranchStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PostgresBranchList contains a list of PostgresBranchs
type PostgresBranchList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PostgresBranch `json:"items"`
}

// Repository type metadata.
var (
	PostgresBranch_Kind             = "PostgresBranch"
	PostgresBranch_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PostgresBranch_Kind}.String()
	PostgresBranch_KindAPIVersion   = PostgresBranch_Kind + "." + CRDGroupVersion.String()
	PostgresBranch_GroupVersionKind = CRDGroupVersion.WithKind(PostgresBranch_Kind)
)

func init() {
	SchemeBuilder.Register(&PostgresBranch{}, &PostgresBranchList{})
}
