// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HTTPURLSpecInitParameters struct {

	// Value of the authorization header that should be sent in the request sent by the wehbook.  It should be of the form <auth type> <credentials>, e.g. Bearer <access_token>. If set to an empty string, no authorization header will be included in the request.
	Authorization *string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Enable/disable SSL certificate validation. Default is true. For self-signed certificates, this field must be false AND the destination server must disable certificate validation as well. For security purposes, it is encouraged to perform secret validation with the HMAC-encoded portion of the payload and acknowledge the risk associated with disabling hostname validation whereby it becomes more likely that requests can be maliciously routed to an unintended host.
	EnableSSLVerification *bool `json:"enableSslVerification,omitempty" tf:"enable_ssl_verification,omitempty"`

	// Shared secret required for HMAC encoding payload. The HMAC-encoded payload will be sent in the header as X-Databricks-Signature: encoded_payload.
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// External HTTPS URL called on event trigger (by using a POST request). Structure of payload depends on the event type, refer to documentation for more details.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type HTTPURLSpecObservation struct {

	// Value of the authorization header that should be sent in the request sent by the wehbook.  It should be of the form <auth type> <credentials>, e.g. Bearer <access_token>. If set to an empty string, no authorization header will be included in the request.
	Authorization *string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Enable/disable SSL certificate validation. Default is true. For self-signed certificates, this field must be false AND the destination server must disable certificate validation as well. For security purposes, it is encouraged to perform secret validation with the HMAC-encoded portion of the payload and acknowledge the risk associated with disabling hostname validation whereby it becomes more likely that requests can be maliciously routed to an unintended host.
	EnableSSLVerification *bool `json:"enableSslVerification,omitempty" tf:"enable_ssl_verification,omitempty"`

	// External HTTPS URL called on event trigger (by using a POST request). Structure of payload depends on the event type, refer to documentation for more details.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type HTTPURLSpecParameters struct {

	// Value of the authorization header that should be sent in the request sent by the wehbook.  It should be of the form <auth type> <credentials>, e.g. Bearer <access_token>. If set to an empty string, no authorization header will be included in the request.
	// +kubebuilder:validation:Optional
	Authorization *string `json:"authorization,omitempty" tf:"authorization,omitempty"`

	// Enable/disable SSL certificate validation. Default is true. For self-signed certificates, this field must be false AND the destination server must disable certificate validation as well. For security purposes, it is encouraged to perform secret validation with the HMAC-encoded portion of the payload and acknowledge the risk associated with disabling hostname validation whereby it becomes more likely that requests can be maliciously routed to an unintended host.
	// +kubebuilder:validation:Optional
	EnableSSLVerification *bool `json:"enableSslVerification,omitempty" tf:"enable_ssl_verification,omitempty"`

	// Shared secret required for HMAC encoding payload. The HMAC-encoded payload will be sent in the header as X-Databricks-Signature: encoded_payload.
	// +kubebuilder:validation:Optional
	SecretSecretRef *v1.SecretKeySelector `json:"secretSecretRef,omitempty" tf:"-"`

	// External HTTPS URL called on event trigger (by using a POST request). Structure of payload depends on the event type, refer to documentation for more details.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type JobSpecInitParameters struct {

	// The personal access token used to authorize webhook's job runs.
	AccessTokenSecretRef v1.SecretKeySelector `json:"accessTokenSecretRef" tf:"-"`

	// ID of the Databricks job that the webhook runs.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/compute/v1beta1.Job
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	JobID *string `json:"jobId,omitempty" tf:"job_id,omitempty"`

	// Reference to a Job in compute to populate jobId.
	// +kubebuilder:validation:Optional
	JobIDRef *v1.Reference `json:"jobIdRef,omitempty" tf:"-"`

	// Selector for a Job in compute to populate jobId.
	// +kubebuilder:validation:Optional
	JobIDSelector *v1.Selector `json:"jobIdSelector,omitempty" tf:"-"`

	// URL of the workspace containing the job that this webhook runs. If not specified, the job’s workspace URL is assumed to be the same as the workspace where the webhook is created.
	WorkspaceURL *string `json:"workspaceUrl,omitempty" tf:"workspace_url,omitempty"`
}

type JobSpecObservation struct {

	// ID of the Databricks job that the webhook runs.
	JobID *string `json:"jobId,omitempty" tf:"job_id,omitempty"`

	// URL of the workspace containing the job that this webhook runs. If not specified, the job’s workspace URL is assumed to be the same as the workspace where the webhook is created.
	WorkspaceURL *string `json:"workspaceUrl,omitempty" tf:"workspace_url,omitempty"`
}

type JobSpecParameters struct {

	// The personal access token used to authorize webhook's job runs.
	// +kubebuilder:validation:Optional
	AccessTokenSecretRef v1.SecretKeySelector `json:"accessTokenSecretRef" tf:"-"`

	// ID of the Databricks job that the webhook runs.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/compute/v1beta1.Job
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	JobID *string `json:"jobId,omitempty" tf:"job_id,omitempty"`

	// Reference to a Job in compute to populate jobId.
	// +kubebuilder:validation:Optional
	JobIDRef *v1.Reference `json:"jobIdRef,omitempty" tf:"-"`

	// Selector for a Job in compute to populate jobId.
	// +kubebuilder:validation:Optional
	JobIDSelector *v1.Selector `json:"jobIdSelector,omitempty" tf:"-"`

	// URL of the workspace containing the job that this webhook runs. If not specified, the job’s workspace URL is assumed to be the same as the workspace where the webhook is created.
	// +kubebuilder:validation:Optional
	WorkspaceURL *string `json:"workspaceUrl,omitempty" tf:"workspace_url,omitempty"`
}

type MlflowWebhookInitParameters struct {

	// Optional description of the MLflow webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The list of events that will trigger execution of Databricks job or POSTing to an URL, for example, MODEL_VERSION_CREATED, MODEL_VERSION_TRANSITIONED_STAGE, TRANSITION_REQUEST_CREATED, etc.  Refer to the Webhooks API documentation for a full list of supported events.
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	HTTPURLSpec *HTTPURLSpecInitParameters `json:"httpUrlSpec,omitempty" tf:"http_url_spec,omitempty"`

	JobSpec *JobSpecInitParameters `json:"jobSpec,omitempty" tf:"job_spec,omitempty"`

	// Name of MLflow model for which webhook will be created. If the model name is not specified, a registry-wide webhook is created that listens for the specified events across all versions of all registered models.
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *MlflowWebhookProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Optional status of webhook. Possible values are ACTIVE, TEST_MODE, DISABLED. Default is ACTIVE.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type MlflowWebhookObservation struct {

	// Optional description of the MLflow webhook.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The list of events that will trigger execution of Databricks job or POSTing to an URL, for example, MODEL_VERSION_CREATED, MODEL_VERSION_TRANSITIONED_STAGE, TRANSITION_REQUEST_CREATED, etc.  Refer to the Webhooks API documentation for a full list of supported events.
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	HTTPURLSpec *HTTPURLSpecObservation `json:"httpUrlSpec,omitempty" tf:"http_url_spec,omitempty"`

	// Unique ID of the MLflow Webhook.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	JobSpec *JobSpecObservation `json:"jobSpec,omitempty" tf:"job_spec,omitempty"`

	// Name of MLflow model for which webhook will be created. If the model name is not specified, a registry-wide webhook is created that listens for the specified events across all versions of all registered models.
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *MlflowWebhookProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Optional status of webhook. Possible values are ACTIVE, TEST_MODE, DISABLED. Default is ACTIVE.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type MlflowWebhookParameters struct {

	// Optional description of the MLflow webhook.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The list of events that will trigger execution of Databricks job or POSTing to an URL, for example, MODEL_VERSION_CREATED, MODEL_VERSION_TRANSITIONED_STAGE, TRANSITION_REQUEST_CREATED, etc.  Refer to the Webhooks API documentation for a full list of supported events.
	// +kubebuilder:validation:Optional
	Events []*string `json:"events,omitempty" tf:"events,omitempty"`

	// +kubebuilder:validation:Optional
	HTTPURLSpec *HTTPURLSpecParameters `json:"httpUrlSpec,omitempty" tf:"http_url_spec,omitempty"`

	// +kubebuilder:validation:Optional
	JobSpec *JobSpecParameters `json:"jobSpec,omitempty" tf:"job_spec,omitempty"`

	// Name of MLflow model for which webhook will be created. If the model name is not specified, a registry-wide webhook is created that listens for the specified events across all versions of all registered models.
	// +kubebuilder:validation:Optional
	ModelName *string `json:"modelName,omitempty" tf:"model_name,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	// +kubebuilder:validation:Optional
	ProviderConfig *MlflowWebhookProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Optional status of webhook. Possible values are ACTIVE, TEST_MODE, DISABLED. Default is ACTIVE.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type MlflowWebhookProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type MlflowWebhookProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type MlflowWebhookProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId" tf:"workspace_id,omitempty"`
}

// MlflowWebhookSpec defines the desired state of MlflowWebhook
type MlflowWebhookSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MlflowWebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MlflowWebhookInitParameters `json:"initProvider,omitempty"`
}

// MlflowWebhookStatus defines the observed state of MlflowWebhook.
type MlflowWebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MlflowWebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MlflowWebhook is the Schema for the MlflowWebhooks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type MlflowWebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.events) || (has(self.initProvider) && has(self.initProvider.events))",message="spec.forProvider.events is a required parameter"
	Spec   MlflowWebhookSpec   `json:"spec"`
	Status MlflowWebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MlflowWebhookList contains a list of MlflowWebhooks
type MlflowWebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MlflowWebhook `json:"items"`
}

// Repository type metadata.
var (
	MlflowWebhook_Kind             = "MlflowWebhook"
	MlflowWebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MlflowWebhook_Kind}.String()
	MlflowWebhook_KindAPIVersion   = MlflowWebhook_Kind + "." + CRDGroupVersion.String()
	MlflowWebhook_GroupVersionKind = CRDGroupVersion.WithKind(MlflowWebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&MlflowWebhook{}, &MlflowWebhookList{})
}
