# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: SQLPermissions
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1beta1/sqlpermissions
  labels:
    testing.upbound.io/example-name: foo_table
  name: foo-table
spec:
  forProvider:
    privilegeAssignments:
    - principal: serge@example.com
      privileges:
      - SELECT
      - MODIFY
    - principal: special group
      privileges:
      - SELECT
    table: foo
