# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: envs.databricks.m.crossplane.io/v1beta1
kind: EnvironmentsWorkspaceBaseEnvironment
metadata:
  annotations:
    meta.upbound.io/example-id: envs/v1beta1/environmentsworkspacebaseenvironment
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    displayName: my-environment
    filepath: /Volumes/catalog/schema/volume/environment.yaml
