FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN sudo apt-get update \
	&& sudo apt-get install -y --no-install-recommends golang-go git-lfs python-is-python3 golang-golang-x-tools \
	&& sudo rm -rf /var/lib/apt/lists/*
