// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccountFederationPolicyInitParameters struct {

	// Description of the federation policy
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (OidcFederationPolicy, optional)
	OidcPolicy *OidcPolicyInitParameters `json:"oidcPolicy,omitempty" tf:"oidc_policy,omitempty"`

	// The ID of the federation policy. Output only
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// The service principal ID that this federation policy applies to. Output only. Only set for service principal federation policies
	ServicePrincipalID *float64 `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

type AccountFederationPolicyObservation struct {

	// Creation time of the federation policy
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Description of the federation policy
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Resource name for the federation policy. Example values include
	// accounts/<account-id>/federationPolicies/my-federation-policy for Account Federation Policies, and
	// accounts/<account-id>/servicePrincipals/<service-principal-id>/federationPolicies/my-federation-policy
	// for Service Principal Federation Policies. Typically an output parameter, which does not need to be
	// specified in create or update requests. If specified in a request, must match the value in the
	// request URL
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (OidcFederationPolicy, optional)
	OidcPolicy *OidcPolicyObservation `json:"oidcPolicy,omitempty" tf:"oidc_policy,omitempty"`

	// The ID of the federation policy. Output only
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// The service principal ID that this federation policy applies to. Output only. Only set for service principal federation policies
	ServicePrincipalID *float64 `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`

	// Unique, immutable id of the federation policy
	UID *string `json:"uid,omitempty" tf:"uid,omitempty"`

	// Last update time of the federation policy
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type AccountFederationPolicyParameters struct {

	// Description of the federation policy
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (OidcFederationPolicy, optional)
	// +kubebuilder:validation:Optional
	OidcPolicy *OidcPolicyParameters `json:"oidcPolicy,omitempty" tf:"oidc_policy,omitempty"`

	// The ID of the federation policy. Output only
	// +kubebuilder:validation:Optional
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// The service principal ID that this federation policy applies to. Output only. Only set for service principal federation policies
	// +kubebuilder:validation:Optional
	ServicePrincipalID *float64 `json:"servicePrincipalId,omitempty" tf:"service_principal_id,omitempty"`
}

type OidcPolicyInitParameters struct {

	// The allowed token audiences, as specified in the 'aud' claim of federated tokens.
	// The audience identifier is intended to represent the recipient of the token.
	// Can be any non-empty string value. As long as the audience in the token matches
	// at least one audience in the policy, the token is considered a match. If audiences
	// is unspecified, defaults to your Databricks account id
	Audiences []*string `json:"audiences,omitempty" tf:"audiences,omitempty"`

	// The required token issuer, as specified in the 'iss' claim of federated tokens
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The public keys used to validate the signature of federated tokens, in JWKS format.
	// Most use cases should not need to specify this field. If jwks_uri and jwks_json
	// are both unspecified (recommended), Databricks automatically fetches the public
	// keys from your issuer’s well known endpoint. Databricks strongly recommends
	// relying on your issuer’s well known endpoint for discovering public keys
	JwksJSON *string `json:"jwksJson,omitempty" tf:"jwks_json,omitempty"`

	// URL of the public keys used to validate the signature of federated tokens, in
	// JWKS format. Most use cases should not need to specify this field. If jwks_uri
	// and jwks_json are both unspecified (recommended), Databricks automatically
	// fetches the public keys from your issuer’s well known endpoint. Databricks
	// strongly recommends relying on your issuer’s well known endpoint for discovering
	// public keys
	JwksURI *string `json:"jwksUri,omitempty" tf:"jwks_uri,omitempty"`

	// The required token subject, as specified in the subject claim of federated tokens.
	// Must be specified for service principal federation policies. Must not be specified
	// for account federation policies
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// The claim that contains the subject of the token. If unspecified, the default value
	// is 'sub'
	SubjectClaim *string `json:"subjectClaim,omitempty" tf:"subject_claim,omitempty"`
}

type OidcPolicyObservation struct {

	// The allowed token audiences, as specified in the 'aud' claim of federated tokens.
	// The audience identifier is intended to represent the recipient of the token.
	// Can be any non-empty string value. As long as the audience in the token matches
	// at least one audience in the policy, the token is considered a match. If audiences
	// is unspecified, defaults to your Databricks account id
	Audiences []*string `json:"audiences,omitempty" tf:"audiences,omitempty"`

	// The required token issuer, as specified in the 'iss' claim of federated tokens
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The public keys used to validate the signature of federated tokens, in JWKS format.
	// Most use cases should not need to specify this field. If jwks_uri and jwks_json
	// are both unspecified (recommended), Databricks automatically fetches the public
	// keys from your issuer’s well known endpoint. Databricks strongly recommends
	// relying on your issuer’s well known endpoint for discovering public keys
	JwksJSON *string `json:"jwksJson,omitempty" tf:"jwks_json,omitempty"`

	// URL of the public keys used to validate the signature of federated tokens, in
	// JWKS format. Most use cases should not need to specify this field. If jwks_uri
	// and jwks_json are both unspecified (recommended), Databricks automatically
	// fetches the public keys from your issuer’s well known endpoint. Databricks
	// strongly recommends relying on your issuer’s well known endpoint for discovering
	// public keys
	JwksURI *string `json:"jwksUri,omitempty" tf:"jwks_uri,omitempty"`

	// The required token subject, as specified in the subject claim of federated tokens.
	// Must be specified for service principal federation policies. Must not be specified
	// for account federation policies
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// The claim that contains the subject of the token. If unspecified, the default value
	// is 'sub'
	SubjectClaim *string `json:"subjectClaim,omitempty" tf:"subject_claim,omitempty"`
}

type OidcPolicyParameters struct {

	// The allowed token audiences, as specified in the 'aud' claim of federated tokens.
	// The audience identifier is intended to represent the recipient of the token.
	// Can be any non-empty string value. As long as the audience in the token matches
	// at least one audience in the policy, the token is considered a match. If audiences
	// is unspecified, defaults to your Databricks account id
	// +kubebuilder:validation:Optional
	Audiences []*string `json:"audiences,omitempty" tf:"audiences,omitempty"`

	// The required token issuer, as specified in the 'iss' claim of federated tokens
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty" tf:"issuer,omitempty"`

	// The public keys used to validate the signature of federated tokens, in JWKS format.
	// Most use cases should not need to specify this field. If jwks_uri and jwks_json
	// are both unspecified (recommended), Databricks automatically fetches the public
	// keys from your issuer’s well known endpoint. Databricks strongly recommends
	// relying on your issuer’s well known endpoint for discovering public keys
	// +kubebuilder:validation:Optional
	JwksJSON *string `json:"jwksJson,omitempty" tf:"jwks_json,omitempty"`

	// URL of the public keys used to validate the signature of federated tokens, in
	// JWKS format. Most use cases should not need to specify this field. If jwks_uri
	// and jwks_json are both unspecified (recommended), Databricks automatically
	// fetches the public keys from your issuer’s well known endpoint. Databricks
	// strongly recommends relying on your issuer’s well known endpoint for discovering
	// public keys
	// +kubebuilder:validation:Optional
	JwksURI *string `json:"jwksUri,omitempty" tf:"jwks_uri,omitempty"`

	// The required token subject, as specified in the subject claim of federated tokens.
	// Must be specified for service principal federation policies. Must not be specified
	// for account federation policies
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`

	// The claim that contains the subject of the token. If unspecified, the default value
	// is 'sub'
	// +kubebuilder:validation:Optional
	SubjectClaim *string `json:"subjectClaim,omitempty" tf:"subject_claim,omitempty"`
}

// AccountFederationPolicySpec defines the desired state of AccountFederationPolicy
type AccountFederationPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountFederationPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountFederationPolicyInitParameters `json:"initProvider,omitempty"`
}

// AccountFederationPolicyStatus defines the observed state of AccountFederationPolicy.
type AccountFederationPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountFederationPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountFederationPolicy is the Schema for the AccountFederationPolicys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type AccountFederationPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountFederationPolicySpec   `json:"spec"`
	Status            AccountFederationPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountFederationPolicyList contains a list of AccountFederationPolicys
type AccountFederationPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountFederationPolicy `json:"items"`
}

// Repository type metadata.
var (
	AccountFederationPolicy_Kind             = "AccountFederationPolicy"
	AccountFederationPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountFederationPolicy_Kind}.String()
	AccountFederationPolicy_KindAPIVersion   = AccountFederationPolicy_Kind + "." + CRDGroupVersion.String()
	AccountFederationPolicy_GroupVersionKind = CRDGroupVersion.WithKind(AccountFederationPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountFederationPolicy{}, &AccountFederationPolicyList{})
}
