apiVersion: unity.databricks.crossplane.io/v1alpha1
kind: GrantMap
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/grantmap
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
spec:
  forProvider:
    grant:
    - principalSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      privileges:
      - CREATE_CATALOG
      - CREATE_EXTERNAL_LOCATION
    - principalSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      privileges:
      - CREATE_RECIPIENT
      - CREATE_SHARE
    metastore: metastore_id
