// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	reConvertTo = regexp.MustCompile(`func \(tr \*([A-Za-z0-9_]+)\) ConvertTo\(`)
)

type methodName string

const (
	mGetCondition          methodName = "GetCondition"
	mSetConditions         methodName = "SetConditions"
	mGetManagementPolicies methodName = "GetManagementPolicies"
	mSetManagementPolicies methodName = "SetManagementPolicies"
)

var requiredMethods = []methodName{
	mGetCondition,
	mSetConditions,
	mGetManagementPolicies,
	mSetManagementPolicies,
}

func main() {
	if len(os.Args) < 2 || strings.TrimSpace(os.Args[1]) == "" {
		panic("usage: go run ./cmd/managedshim/main.go <apis-root>")
	}
	root := os.Args[1]
	absRoot, err := filepath.Abs(root)
	if err != nil {
		panic(fmt.Sprintf("cannot determine absolute path for %q: %v", root, err))
	}

	if err := walkForConversionSpokes(absRoot); err != nil {
		panic(err)
	}
}

func walkForConversionSpokes(root string) error {
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		path := filepath.Join(root, entry.Name())
		if entry.IsDir() {
			if err := walkForConversionSpokes(path); err != nil {
				return err
			}
			continue
		}
		if entry.Name() != "zz_generated.conversion_spokes.go" {
			continue
		}
		if err := ensureShim(filepath.Dir(path), path); err != nil {
			return err
		}
	}
	return nil
}

func ensureShim(pkgDir, spokeFile string) error {
	types, err := parseTypesFromSpokes(spokeFile)
	if err != nil {
		return err
	}
	if len(types) == 0 {
		return nil
	}

	missingByType := map[string][]methodName{}
	for _, t := range types {
		for _, m := range requiredMethods {
			has, err := packageHasMethod(pkgDir, t, m)
			if err != nil {
				return err
			}
			if !has {
				missingByType[t] = append(missingByType[t], m)
			}
		}
	}

	shimPath := filepath.Join(pkgDir, "zz_generated.managed_shim.go")
	if len(missingByType) == 0 {
		// #nosec G304,G703 -- shimPath is derived from checked-in package directories.
		_ = os.Remove(shimPath)
		return nil
	}

	content := renderShim(missingByType)
	// #nosec G304,G703 -- shimPath is derived from checked-in package directories.
	return os.WriteFile(shimPath, []byte(content), 0600)
}

func parseTypesFromSpokes(path string) ([]string, error) {
	// #nosec G304,G703 -- path is discovered from the checked-in repository tree.
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	matches := reConvertTo.FindAllStringSubmatch(string(b), -1)
	set := map[string]struct{}{}
	for _, m := range matches {
		if len(m) == 2 {
			set[m[1]] = struct{}{}
		}
	}
	out := make([]string, 0, len(set))
	for t := range set {
		out = append(out, t)
	}
	sort.Strings(out)
	return out, nil
}

func packageHasMethod(pkgDir, typeName string, method methodName) (bool, error) {
	glob := filepath.Join(pkgDir, "*.go")
	files, err := filepath.Glob(glob)
	if err != nil {
		return false, fmt.Errorf("glob %s: %w", glob, err)
	}
	sig := fmt.Sprintf("func (mg *%s) %s(", typeName, method)
	for _, f := range files {
		if strings.HasSuffix(f, "zz_generated.managed_shim.go") {
			continue
		}
		// #nosec G304,G703 -- files are sourced from the repository's own package directory.
		b, err := os.ReadFile(f)
		if err != nil {
			return false, fmt.Errorf("read %s: %w", f, err)
		}
		if strings.Contains(string(b), sig) {
			return true, nil
		}
	}
	return false, nil
}

func renderShim(missingByType map[string][]methodName) string {
	types := make([]string, 0, len(missingByType))
	for t := range missingByType {
		types = append(types, t)
	}
	sort.Strings(types)

	var sb strings.Builder
	sb.WriteString("// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>\n")
	sb.WriteString("//\n")
	sb.WriteString("// SPDX-License-Identifier: Apache-2.0\n\n")
	sb.WriteString("// Code generated by managedshim. DO NOT EDIT.\n\n")
	sb.WriteString("package v1beta1\n\n")
	sb.WriteString("import xpv2 \"github.com/crossplane/crossplane/apis/v2/core/v2\"\n\n")

	for _, t := range types {
		methods := missingByType[t]
		sort.Slice(methods, func(i, j int) bool { return methods[i] < methods[j] })
		for _, m := range methods {
			switch m {
			case mGetCondition:
				fmt.Fprintf(&sb, "func (mg *%s) GetCondition(ct xpv2.ConditionType) xpv2.Condition {\n", t)
				fmt.Fprintln(&sb, "\treturn mg.Status.GetCondition(ct)")
				fmt.Fprintln(&sb, "}")
				fmt.Fprintln(&sb)
			case mSetConditions:
				fmt.Fprintf(&sb, "func (mg *%s) SetConditions(c ...xpv2.Condition) {\n", t)
				fmt.Fprintln(&sb, "\tmg.Status.SetConditions(c...)")
				fmt.Fprintln(&sb, "}")
				fmt.Fprintln(&sb)
			case mGetManagementPolicies:
				fmt.Fprintf(&sb, "func (mg *%s) GetManagementPolicies() xpv2.ManagementPolicies {\n", t)
				fmt.Fprintln(&sb, "\treturn mg.Spec.ManagementPolicies")
				fmt.Fprintln(&sb, "}")
				fmt.Fprintln(&sb)
			case mSetManagementPolicies:
				fmt.Fprintf(&sb, "func (mg *%s) SetManagementPolicies(r xpv2.ManagementPolicies) {\n", t)
				fmt.Fprintln(&sb, "\tmg.Spec.ManagementPolicies = r")
				fmt.Fprintln(&sb, "}")
				fmt.Fprintln(&sb)
			}
		}
	}
	return sb.String()
}
