apiVersion: sql.databricks.crossplane.io/v1alpha1
kind: SQLEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1alpha1/sqlendpoint
  labels:
    testing.upbound.io/example-name: sql-endpoint-test
  name: sql-endpoint-test
spec:
  forProvider:
    clusterSize: 2X-Small # "2X-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "2X-Large", "3X-Large", "4X-Large".
    autoStopMins: 20
    enableServerlessCompute: true
    spotInstancePolicy: COST_OPTIMIZED #Optional
    maxNumClusters: 1
    name: sql-endpoint-test-1
    tags:
    - customTags:
      - key: City
        value: Vancouver