// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha2 "github.com/glalanne/provider-databricks/apis/cluster/apps/v1alpha2"
	v1alpha2compute "github.com/glalanne/provider-databricks/apis/cluster/compute/v1alpha2"
	v1alpha2databases "github.com/glalanne/provider-databricks/apis/cluster/databases/v1alpha2"
	v1alpha2deployment "github.com/glalanne/provider-databricks/apis/cluster/deployment/v1alpha2"
	v1alpha2finops "github.com/glalanne/provider-databricks/apis/cluster/finops/v1alpha2"
	v1alpha2log "github.com/glalanne/provider-databricks/apis/cluster/log/v1alpha2"
	v1alpha2mlflow "github.com/glalanne/provider-databricks/apis/cluster/mlflow/v1alpha2"
	v1alpha2mosaic "github.com/glalanne/provider-databricks/apis/cluster/mosaic/v1alpha2"
	v1alpha2oauth "github.com/glalanne/provider-databricks/apis/cluster/oauth/v1alpha2"
	v1alpha2security "github.com/glalanne/provider-databricks/apis/cluster/security/v1alpha2"
	v1alpha2serving "github.com/glalanne/provider-databricks/apis/cluster/serving/v1alpha2"
	v1alpha2settings "github.com/glalanne/provider-databricks/apis/cluster/settings/v1alpha2"
	v1alpha2sharing "github.com/glalanne/provider-databricks/apis/cluster/sharing/v1alpha2"
	v1alpha2sql "github.com/glalanne/provider-databricks/apis/cluster/sql/v1alpha2"
	v1alpha2storage "github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha2"
	v1alpha2unity "github.com/glalanne/provider-databricks/apis/cluster/unity/v1alpha2"
	v1alpha1 "github.com/glalanne/provider-databricks/apis/cluster/v1alpha1"
	v1beta1 "github.com/glalanne/provider-databricks/apis/cluster/v1beta1"
	v1alpha2workspace "github.com/glalanne/provider-databricks/apis/cluster/workspace/v1alpha2"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha2.SchemeBuilder.AddToScheme,
		v1alpha2compute.SchemeBuilder.AddToScheme,
		v1alpha2databases.SchemeBuilder.AddToScheme,
		v1alpha2deployment.SchemeBuilder.AddToScheme,
		v1alpha2finops.SchemeBuilder.AddToScheme,
		v1alpha2log.SchemeBuilder.AddToScheme,
		v1alpha2mlflow.SchemeBuilder.AddToScheme,
		v1alpha2mosaic.SchemeBuilder.AddToScheme,
		v1alpha2oauth.SchemeBuilder.AddToScheme,
		v1alpha2security.SchemeBuilder.AddToScheme,
		v1alpha2serving.SchemeBuilder.AddToScheme,
		v1alpha2settings.SchemeBuilder.AddToScheme,
		v1alpha2sharing.SchemeBuilder.AddToScheme,
		v1alpha2sql.SchemeBuilder.AddToScheme,
		v1alpha2storage.SchemeBuilder.AddToScheme,
		v1alpha2unity.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha2workspace.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
