apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: CatalogWorkspaceBinding
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/catalogworkspacebinding
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
  namespace: upbound-system
spec:
  forProvider:
    securableNameSelector:
      matchLabels:
        testing.upbound.io/example-name: sandbox
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: other

---

apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/catalogworkspacebinding
  labels:
    testing.upbound.io/example-name: sandbox
  name: sandbox
  namespace: upbound-system
spec:
  forProvider:
    isolationMode: ISOLATED
    name: sandbox
