apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: StorageCredential
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/storagecredential
  labels:
    testing.upbound.io/example-name: external
  name: external
  namespace: upbound-system
spec:
  forProvider:
    awsIamRole:
    - roleArn: ${aws_iam_role.external_data_access.arn}
    comment: Managed by TF
    name: ${aws_iam_role.external_data_access.name}

---

apiVersion: unity.databricks.m.crossplane.io/v1alpha1
kind: GrantMap
metadata:
  annotations:
    meta.upbound.io/example-id: unity/v1alpha1/storagecredential
  labels:
    testing.upbound.io/example-name: external_creds
  name: external-creds
  namespace: upbound-system
spec:
  forProvider:
    grant:
    - principalSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      privileges:
      - CREATE_EXTERNAL_TABLE
    storageCredentialSelector:
      matchLabels:
        testing.upbound.io/example-name: external
