# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: workspace.databricks.m.crossplane.io/v1alpha2
kind: NotificationDestination
metadata:
  annotations:
    meta.upbound.io/example-id: workspace/v1alpha2/notificationdestination
  labels:
    testing.upbound.io/example-name: ndresource
  name: ndresource
  namespace: upbound-system
spec:
  forProvider:
    config:
      email:
        addresses:
        - abc@gmail.com
    displayName: Notification Destination
