apiVersion: deployment.databricks.crossplane.io/v1alpha1
kind: MwsCredentials
metadata:
  annotations:
    meta.upbound.io/example-id: deployment/v1alpha1/mwscredentials
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    credentialsName: ${var.prefix}-creds
    provider: ${databricks.mws}
    roleArn: ${aws_iam_role.cross_account_role.arn}
