// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConnectionInitParameters struct {

	// User-provided free-form text description. Change forces creation of a new resource.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The type of connection. Possible values are: BIGQUERY, CONFLUENCE, DATABRICKS, GA4_RAW_DATA, GITHUB, GLUE, HIVE_METASTORE, HTTP, HUBSPOT, META_MARKETING, MYSQL, ORACLE, OUTLOOK, POSTGRESQL, POWER_BI, REDSHIFT, SALESFORCE, SALESFORCE_DATA_CLOUD, SERVICENOW, SMARTSHEET, SNOWFLAKE, SQLDW, SQLSERVER, TERADATA, WORKDAY_RAAS, or ZENDESK. For an up-to-date list of connection types and required options, see the documentation. Change forces creation of a new resource.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// Connection environment settings. This block consists of the following fields:
	EnvironmentSettings *EnvironmentSettingsInitParameters `json:"environmentSettings,omitempty" tf:"environment_settings,omitempty"`

	// Name of the connection.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Options map[string]*string `json:"optionsSecretRef,omitempty" tf:"-"`

	// Username of current owner of the connection.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// A map of key-value properties attached to the securable. Change forces creation of a new resource.
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *ConnectionProviderConfigInitParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// If the connection is read only. Change forces creation of a new resource.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`
}

type ConnectionObservation struct {

	// User-provided free-form text description. Change forces creation of a new resource.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Unique identifier of the Connection.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// The type of connection. Possible values are: BIGQUERY, CONFLUENCE, DATABRICKS, GA4_RAW_DATA, GITHUB, GLUE, HIVE_METASTORE, HTTP, HUBSPOT, META_MARKETING, MYSQL, ORACLE, OUTLOOK, POSTGRESQL, POWER_BI, REDSHIFT, SALESFORCE, SALESFORCE_DATA_CLOUD, SERVICENOW, SMARTSHEET, SNOWFLAKE, SQLDW, SQLSERVER, TERADATA, WORKDAY_RAAS, or ZENDESK. For an up-to-date list of connection types and required options, see the documentation. Change forces creation of a new resource.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// Time at which this connection was created, in epoch milliseconds.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Username of connection creator.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// The type of credential.
	CredentialType *string `json:"credentialType,omitempty" tf:"credential_type,omitempty"`

	// Connection environment settings. This block consists of the following fields:
	EnvironmentSettings *EnvironmentSettingsObservation `json:"environmentSettings,omitempty" tf:"environment_settings,omitempty"`

	// Full name of connection.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// ID of this connection in form of <metastore_id>|<name>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique identifier of parent metastore.
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`

	// Name of the connection.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Username of current owner of the connection.
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// A map of key-value properties attached to the securable. Change forces creation of a new resource.
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	ProviderConfig *ConnectionProviderConfigObservation `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Status of an asynchronously provisioned resource. This block consists of the following fields:
	ProvisioningInfo []ConnectionProvisioningInfoObservation `json:"provisioningInfo,omitempty" tf:"provisioning_info,omitempty"`

	// If the connection is read only. Change forces creation of a new resource.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// Securable type.
	SecurableType *string `json:"securableType,omitempty" tf:"securable_type,omitempty"`

	// URL of the remote data source, extracted from options.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Time at which this connection was updated, in epoch milliseconds.
	UpdatedAt *float64 `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Username of user who last modified connection.
	UpdatedBy *string `json:"updatedBy,omitempty" tf:"updated_by,omitempty"`
}

type ConnectionParameters struct {

	// User-provided free-form text description. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The type of connection. Possible values are: BIGQUERY, CONFLUENCE, DATABRICKS, GA4_RAW_DATA, GITHUB, GLUE, HIVE_METASTORE, HTTP, HUBSPOT, META_MARKETING, MYSQL, ORACLE, OUTLOOK, POSTGRESQL, POWER_BI, REDSHIFT, SALESFORCE, SALESFORCE_DATA_CLOUD, SERVICENOW, SMARTSHEET, SNOWFLAKE, SQLDW, SQLSERVER, TERADATA, WORKDAY_RAAS, or ZENDESK. For an up-to-date list of connection types and required options, see the documentation. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// Connection environment settings. This block consists of the following fields:
	// +kubebuilder:validation:Optional
	EnvironmentSettings *EnvironmentSettingsParameters `json:"environmentSettings,omitempty" tf:"environment_settings,omitempty"`

	// Name of the connection.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A map of key-value properties attached to the securable. The required keys depend on the connection type, e.g. host, port, user, password, authorization_endpoint, client_id, client_secret, or GoogleServiceAccountKeyJson. Please consult the documentation for the required options. This field is sensitive.
	// +kubebuilder:validation:Optional
	OptionsSecretRef *v2.SecretReference `json:"optionsSecretRef,omitempty" tf:"-"`

	// Username of current owner of the connection.
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// A map of key-value properties attached to the securable. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Properties map[string]*string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Configure the provider for management through account provider. This block consists of the following fields:
	// +kubebuilder:validation:Optional
	ProviderConfig *ConnectionProviderConfigParameters `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// If the connection is read only. Change forces creation of a new resource.
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`
}

type ConnectionProviderConfigInitParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ConnectionProviderConfigObservation struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ConnectionProviderConfigParameters struct {

	// Workspace ID which the resource belongs to. This workspace must be part of the account which the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type ConnectionProvisioningInfoInitParameters struct {
}

type ConnectionProvisioningInfoObservation struct {

	// The provisioning state of the resource. Possible values are: ACTIVE, DEGRADED, DELETING, FAILED, PROVISIONING, or UPDATING.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type ConnectionProvisioningInfoParameters struct {
}

type EnvironmentSettingsInitParameters struct {

	// Environment version.
	EnvironmentVersion *string `json:"environmentVersion,omitempty" tf:"environment_version,omitempty"`

	// List of Java dependencies.
	JavaDependencies []*string `json:"javaDependencies,omitempty" tf:"java_dependencies,omitempty"`
}

type EnvironmentSettingsObservation struct {

	// Environment version.
	EnvironmentVersion *string `json:"environmentVersion,omitempty" tf:"environment_version,omitempty"`

	// List of Java dependencies.
	JavaDependencies []*string `json:"javaDependencies,omitempty" tf:"java_dependencies,omitempty"`
}

type EnvironmentSettingsParameters struct {

	// Environment version.
	// +kubebuilder:validation:Optional
	EnvironmentVersion *string `json:"environmentVersion,omitempty" tf:"environment_version,omitempty"`

	// List of Java dependencies.
	// +kubebuilder:validation:Optional
	JavaDependencies []*string `json:"javaDependencies,omitempty" tf:"java_dependencies,omitempty"`
}

// ConnectionSpec defines the desired state of Connection
type ConnectionSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectionInitParameters `json:"initProvider,omitempty"`
}

// ConnectionStatus defines the observed state of Connection.
type ConnectionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Connection is the Schema for the Connections API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type Connection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConnectionSpec   `json:"spec"`
	Status            ConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectionList contains a list of Connections
type ConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Connection `json:"items"`
}

// Repository type metadata.
var (
	Connection_Kind             = "Connection"
	Connection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Connection_Kind}.String()
	Connection_KindAPIVersion   = Connection_Kind + "." + CRDGroupVersion.String()
	Connection_GroupVersionKind = CRDGroupVersion.WithKind(Connection_Kind)
)

func init() {
	SchemeBuilder.Register(&Connection{}, &ConnectionList{})
}
