# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: sql.databricks.m.crossplane.io/v1beta1
kind: SQLVisualization
metadata:
  annotations:
    meta.upbound.io/example-id: sql/v1beta1/sqlvisualization
  labels:
    testing.upbound.io/example-name: q1v1
  name: q1v1
  namespace: upbound-system
spec:
  forProvider:
    description: Some Description
    name: My Table
    options: |-
      ${jsonencode(
          {
            "itemsPerPage" : 25,
            "columns" : [
              {
                "name" : "p1",
                "type" : "string"
                "title" : "Parameter 1",
                "displayAs" : "string",
              },
              {
                "name" : "p2",
                "type" : "string"
                "title" : "Parameter 2",
                "displayAs" : "link",
                "highlightLinks" : true,
              }
            ]
          }
        )}
    queryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: q1
    type: table
