# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: dr.databricks.m.crossplane.io/v1beta1
kind: DisasterRecoveryFailoverGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dr/v1beta1/disasterrecoveryfailovergroup
  labels:
    testing.upbound.io/example-name: this
  name: this
  namespace: upbound-system
spec:
  forProvider:
    failoverGroupId: accounting-failover-group
    initialPrimaryRegion: us-east-1
    regions:
    - us-east-1
    - us-west-2
    workspaceSets:
    - name: accounting
      replicateWorkspaceAssets: true
      workspaceIds:
      - "1234567890123456"
      - "6543210987654321"
