apiVersion: compute.databricks.crossplane.io/v1alpha1
kind: ClusterPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/clusterpolicy
  labels:
    testing.upbound.io/example-name: fair_use
  name: fair-use
spec:
  forProvider:
    definition: ${jsonencode(merge(local.default_policy, var.policy_overrides))}
    libraries:
    - pypi:
      - package: databricks-sdk==0.12.0
    - maven:
      - coordinates: com.oracle.database.jdbc:ojdbc8:XXXX
    name: ${var.team} cluster policy

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/clusterpolicy
  labels:
    testing.upbound.io/example-name: can_use_cluster_policyinstance_profile
  name: can-use-cluster-policyinstance-profile
spec:
  forProvider:
    accessControl:
    - groupName: ${var.team}
      permissionLevel: CAN_USE
    clusterPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: fair_use
