//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironment) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironment.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironment) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironment {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters) {
	*out = *in
	if in.CPUWorkspaceBaseEnvironment != nil {
		in, out := &in.CPUWorkspaceBaseEnvironment, &out.CPUWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.CPUWorkspaceBaseEnvironmentRef != nil {
		in, out := &in.CPUWorkspaceBaseEnvironmentRef, &out.CPUWorkspaceBaseEnvironmentRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUWorkspaceBaseEnvironmentSelector != nil {
		in, out := &in.CPUWorkspaceBaseEnvironmentSelector, &out.CPUWorkspaceBaseEnvironmentSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GpuWorkspaceBaseEnvironment != nil {
		in, out := &in.GpuWorkspaceBaseEnvironment, &out.GpuWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.GpuWorkspaceBaseEnvironmentRef != nil {
		in, out := &in.GpuWorkspaceBaseEnvironmentRef, &out.GpuWorkspaceBaseEnvironmentRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.GpuWorkspaceBaseEnvironmentSelector != nil {
		in, out := &in.GpuWorkspaceBaseEnvironmentSelector, &out.GpuWorkspaceBaseEnvironmentSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentList) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentsDefaultWorkspaceBaseEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentList.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentList) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentObservation) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentObservation) {
	*out = *in
	if in.CPUWorkspaceBaseEnvironment != nil {
		in, out := &in.CPUWorkspaceBaseEnvironment, &out.CPUWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.GpuWorkspaceBaseEnvironment != nil {
		in, out := &in.GpuWorkspaceBaseEnvironment, &out.GpuWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentObservation.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentObservation) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentParameters) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentParameters) {
	*out = *in
	if in.CPUWorkspaceBaseEnvironment != nil {
		in, out := &in.CPUWorkspaceBaseEnvironment, &out.CPUWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.CPUWorkspaceBaseEnvironmentRef != nil {
		in, out := &in.CPUWorkspaceBaseEnvironmentRef, &out.CPUWorkspaceBaseEnvironmentRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUWorkspaceBaseEnvironmentSelector != nil {
		in, out := &in.CPUWorkspaceBaseEnvironmentSelector, &out.CPUWorkspaceBaseEnvironmentSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GpuWorkspaceBaseEnvironment != nil {
		in, out := &in.GpuWorkspaceBaseEnvironment, &out.GpuWorkspaceBaseEnvironment
		*out = new(string)
		**out = **in
	}
	if in.GpuWorkspaceBaseEnvironmentRef != nil {
		in, out := &in.GpuWorkspaceBaseEnvironmentRef, &out.GpuWorkspaceBaseEnvironmentRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.GpuWorkspaceBaseEnvironmentSelector != nil {
		in, out := &in.GpuWorkspaceBaseEnvironmentSelector, &out.GpuWorkspaceBaseEnvironmentSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(ProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentParameters.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentParameters) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentSpec) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentSpec.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentSpec) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentStatus) DeepCopyInto(out *EnvironmentsDefaultWorkspaceBaseEnvironmentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsDefaultWorkspaceBaseEnvironmentStatus.
func (in *EnvironmentsDefaultWorkspaceBaseEnvironmentStatus) DeepCopy() *EnvironmentsDefaultWorkspaceBaseEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsDefaultWorkspaceBaseEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironment) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironment.
func (in *EnvironmentsWorkspaceBaseEnvironment) DeepCopy() *EnvironmentsWorkspaceBaseEnvironment {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentsWorkspaceBaseEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentInitParameters) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentInitParameters) {
	*out = *in
	if in.BaseEnvironmentType != nil {
		in, out := &in.BaseEnvironmentType, &out.BaseEnvironmentType
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Filepath != nil {
		in, out := &in.Filepath, &out.Filepath
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkspaceBaseEnvironmentID != nil {
		in, out := &in.WorkspaceBaseEnvironmentID, &out.WorkspaceBaseEnvironmentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentInitParameters.
func (in *EnvironmentsWorkspaceBaseEnvironmentInitParameters) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentList) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentsWorkspaceBaseEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentList.
func (in *EnvironmentsWorkspaceBaseEnvironmentList) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentsWorkspaceBaseEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentObservation) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentObservation) {
	*out = *in
	if in.BaseEnvironmentType != nil {
		in, out := &in.BaseEnvironmentType, &out.BaseEnvironmentType
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.CreatorUserID != nil {
		in, out := &in.CreatorUserID, &out.CreatorUserID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EffectiveBaseEnvironmentType != nil {
		in, out := &in.EffectiveBaseEnvironmentType, &out.EffectiveBaseEnvironmentType
		*out = new(string)
		**out = **in
	}
	if in.Filepath != nil {
		in, out := &in.Filepath, &out.Filepath
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.LastUpdatedUserID != nil {
		in, out := &in.LastUpdatedUserID, &out.LastUpdatedUserID
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SpecObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.WorkspaceBaseEnvironmentID != nil {
		in, out := &in.WorkspaceBaseEnvironmentID, &out.WorkspaceBaseEnvironmentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentObservation.
func (in *EnvironmentsWorkspaceBaseEnvironmentObservation) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentParameters) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentParameters) {
	*out = *in
	if in.BaseEnvironmentType != nil {
		in, out := &in.BaseEnvironmentType, &out.BaseEnvironmentType
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Filepath != nil {
		in, out := &in.Filepath, &out.Filepath
		*out = new(string)
		**out = **in
	}
	if in.ProviderConfig != nil {
		in, out := &in.ProviderConfig, &out.ProviderConfig
		*out = new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkspaceBaseEnvironmentID != nil {
		in, out := &in.WorkspaceBaseEnvironmentID, &out.WorkspaceBaseEnvironmentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentParameters.
func (in *EnvironmentsWorkspaceBaseEnvironmentParameters) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters.
func (in *EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentSpec) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentSpec.
func (in *EnvironmentsWorkspaceBaseEnvironmentSpec) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentsWorkspaceBaseEnvironmentStatus) DeepCopyInto(out *EnvironmentsWorkspaceBaseEnvironmentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentsWorkspaceBaseEnvironmentStatus.
func (in *EnvironmentsWorkspaceBaseEnvironmentStatus) DeepCopy() *EnvironmentsWorkspaceBaseEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentsWorkspaceBaseEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigInitParameters) DeepCopyInto(out *ProviderConfigInitParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigInitParameters.
func (in *ProviderConfigInitParameters) DeepCopy() *ProviderConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigObservation) DeepCopyInto(out *ProviderConfigObservation) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigObservation.
func (in *ProviderConfigObservation) DeepCopy() *ProviderConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigParameters) DeepCopyInto(out *ProviderConfigParameters) {
	*out = *in
	if in.WorkspaceID != nil {
		in, out := &in.WorkspaceID, &out.WorkspaceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigParameters.
func (in *ProviderConfigParameters) DeepCopy() *ProviderConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecInitParameters) DeepCopyInto(out *SpecInitParameters) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnvironmentVersion != nil {
		in, out := &in.EnvironmentVersion, &out.EnvironmentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecInitParameters.
func (in *SpecInitParameters) DeepCopy() *SpecInitParameters {
	if in == nil {
		return nil
	}
	out := new(SpecInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecObservation) DeepCopyInto(out *SpecObservation) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnvironmentVersion != nil {
		in, out := &in.EnvironmentVersion, &out.EnvironmentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecObservation.
func (in *SpecObservation) DeepCopy() *SpecObservation {
	if in == nil {
		return nil
	}
	out := new(SpecObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecParameters) DeepCopyInto(out *SpecParameters) {
	*out = *in
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnvironmentVersion != nil {
		in, out := &in.EnvironmentVersion, &out.EnvironmentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecParameters.
func (in *SpecParameters) DeepCopy() *SpecParameters {
	if in == nil {
		return nil
	}
	out := new(SpecParameters)
	in.DeepCopyInto(out)
	return out
}
