apiVersion: security.databricks.crossplane.io/v1alpha1
kind: GroupInstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/groupinstanceprofile
  labels:
    testing.upbound.io/example-name: my_group_instance_profile
  name: my-group-instance-profile
spec:
  forProvider:
    groupId: ${databricks_group.my_group.id}
    instanceProfileId: ${databricks_instance_profile.instance_profile.id}

---

apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/groupinstanceprofile
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
spec:
  forProvider:
    displayName: my_group_name

---

apiVersion: deployment.databricks.crossplane.io/v1alpha1
kind: InstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/groupinstanceprofile
  labels:
    testing.upbound.io/example-name: instance_profile
  name: instance-profile
spec:
  forProvider:
    instanceProfileArn: my_instance_profile_arn
