// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LibraryCranInitParameters_2 struct {

	// The name of the CRAN package to install.
	Package *string `json:"package,omitempty" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default CRAN repo is used.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryCranObservation_2 struct {

	// The name of the CRAN package to install.
	Package *string `json:"package,omitempty" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default CRAN repo is used.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryCranParameters_2 struct {

	// The name of the CRAN package to install.
	// +kubebuilder:validation:Optional
	Package *string `json:"package" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default CRAN repo is used.
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryInitParameters_2 struct {

	// ID of the databricks_cluster to install the library on.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/compute/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Configuration block for a CRAN library. The block consists of the following fields:
	Cran []LibraryCranInitParameters_2 `json:"cran,omitempty" tf:"cran,omitempty"`

	// Path to the EGG library. Installing Python egg files is deprecated and is not supported in Databricks Runtime 14.0 and above. Use whl or pypi instead.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.DbfsFile
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("dbfs_path",true)
	Egg *string `json:"egg,omitempty" tf:"egg,omitempty"`

	// Reference to a DbfsFile in storage to populate egg.
	// +kubebuilder:validation:Optional
	EggRef *v1.Reference `json:"eggRef,omitempty" tf:"-"`

	// Selector for a DbfsFile in storage to populate egg.
	// +kubebuilder:validation:Optional
	EggSelector *v1.Selector `json:"eggSelector,omitempty" tf:"-"`

	// Path to the JAR library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.jar, /Volumes/path/to/library.jar or s3://my-bucket/library.jar. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.File
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("path",false)
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// Reference to a File in storage to populate jar.
	// +kubebuilder:validation:Optional
	JarRef *v1.Reference `json:"jarRef,omitempty" tf:"-"`

	// Selector for a File in storage to populate jar.
	// +kubebuilder:validation:Optional
	JarSelector *v1.Selector `json:"jarSelector,omitempty" tf:"-"`

	// Configuration block for a Maven library. The block consists of the following fields:
	Maven []LibraryMavenInitParameters_2 `json:"maven,omitempty" tf:"maven,omitempty"`

	// Configuration block for management through the account provider. This block consists of the following fields:
	ProviderConfig []LibraryProviderConfigInitParameters_2 `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Configuration block for a PyPI library. The block consists of the following fields:
	Pypi []LibraryPypiInitParameters_2 `json:"pypi,omitempty" tf:"pypi,omitempty"`

	// Path to the requirements.txt file. Only Workspace paths and Unity Catalog Volumes paths are supported. For example: /Workspace/path/to/requirements.txt or /Volumes/path/to/requirements.txt. Requires a cluster with DBR 15.0+.
	Requirements *string `json:"requirements,omitempty" tf:"requirements,omitempty"`

	// Path to the wheel library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.whl, /Volumes/path/to/library.whl or s3://my-bucket/library.whl. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.File
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("path",false)
	Whl *string `json:"whl,omitempty" tf:"whl,omitempty"`

	// Reference to a File in storage to populate whl.
	// +kubebuilder:validation:Optional
	WhlRef *v1.Reference `json:"whlRef,omitempty" tf:"-"`

	// Selector for a File in storage to populate whl.
	// +kubebuilder:validation:Optional
	WhlSelector *v1.Selector `json:"whlSelector,omitempty" tf:"-"`
}

type LibraryMavenInitParameters_2 struct {

	// Gradle-style Maven coordinates. For example: org.jsoup:jsoup:1.7.2.
	Coordinates *string `json:"coordinates,omitempty" tf:"coordinates,omitempty"`

	// List of dependencies to exclude. For example: ["slf4j:slf4j", "*:hadoop-client"]. See Maven dependency exclusions for more information.
	Exclusions []*string `json:"exclusions,omitempty" tf:"exclusions,omitempty"`

	// Maven repository to install the Maven package from. If omitted, both Maven Central Repository and Spark Packages are searched.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryMavenObservation_2 struct {

	// Gradle-style Maven coordinates. For example: org.jsoup:jsoup:1.7.2.
	Coordinates *string `json:"coordinates,omitempty" tf:"coordinates,omitempty"`

	// List of dependencies to exclude. For example: ["slf4j:slf4j", "*:hadoop-client"]. See Maven dependency exclusions for more information.
	Exclusions []*string `json:"exclusions,omitempty" tf:"exclusions,omitempty"`

	// Maven repository to install the Maven package from. If omitted, both Maven Central Repository and Spark Packages are searched.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryMavenParameters_2 struct {

	// Gradle-style Maven coordinates. For example: org.jsoup:jsoup:1.7.2.
	// +kubebuilder:validation:Optional
	Coordinates *string `json:"coordinates" tf:"coordinates,omitempty"`

	// List of dependencies to exclude. For example: ["slf4j:slf4j", "*:hadoop-client"]. See Maven dependency exclusions for more information.
	// +kubebuilder:validation:Optional
	Exclusions []*string `json:"exclusions,omitempty" tf:"exclusions,omitempty"`

	// Maven repository to install the Maven package from. If omitted, both Maven Central Repository and Spark Packages are searched.
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryObservation_2 struct {

	// ID of the databricks_cluster to install the library on.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Configuration block for a CRAN library. The block consists of the following fields:
	Cran []LibraryCranObservation_2 `json:"cran,omitempty" tf:"cran,omitempty"`

	// Path to the EGG library. Installing Python egg files is deprecated and is not supported in Databricks Runtime 14.0 and above. Use whl or pypi instead.
	Egg *string `json:"egg,omitempty" tf:"egg,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Path to the JAR library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.jar, /Volumes/path/to/library.jar or s3://my-bucket/library.jar. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// Configuration block for a Maven library. The block consists of the following fields:
	Maven []LibraryMavenObservation_2 `json:"maven,omitempty" tf:"maven,omitempty"`

	// Configuration block for management through the account provider. This block consists of the following fields:
	ProviderConfig []LibraryProviderConfigObservation_2 `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Configuration block for a PyPI library. The block consists of the following fields:
	Pypi []LibraryPypiObservation_2 `json:"pypi,omitempty" tf:"pypi,omitempty"`

	// Path to the requirements.txt file. Only Workspace paths and Unity Catalog Volumes paths are supported. For example: /Workspace/path/to/requirements.txt or /Volumes/path/to/requirements.txt. Requires a cluster with DBR 15.0+.
	Requirements *string `json:"requirements,omitempty" tf:"requirements,omitempty"`

	// Path to the wheel library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.whl, /Volumes/path/to/library.whl or s3://my-bucket/library.whl. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	Whl *string `json:"whl,omitempty" tf:"whl,omitempty"`
}

type LibraryParameters_2 struct {

	// ID of the databricks_cluster to install the library on.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/compute/v1alpha1.Cluster
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Cluster in compute to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// Configuration block for a CRAN library. The block consists of the following fields:
	// +kubebuilder:validation:Optional
	Cran []LibraryCranParameters_2 `json:"cran,omitempty" tf:"cran,omitempty"`

	// Path to the EGG library. Installing Python egg files is deprecated and is not supported in Databricks Runtime 14.0 and above. Use whl or pypi instead.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.DbfsFile
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("dbfs_path",true)
	// +kubebuilder:validation:Optional
	Egg *string `json:"egg,omitempty" tf:"egg,omitempty"`

	// Reference to a DbfsFile in storage to populate egg.
	// +kubebuilder:validation:Optional
	EggRef *v1.Reference `json:"eggRef,omitempty" tf:"-"`

	// Selector for a DbfsFile in storage to populate egg.
	// +kubebuilder:validation:Optional
	EggSelector *v1.Selector `json:"eggSelector,omitempty" tf:"-"`

	// Path to the JAR library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.jar, /Volumes/path/to/library.jar or s3://my-bucket/library.jar. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.File
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("path",false)
	// +kubebuilder:validation:Optional
	Jar *string `json:"jar,omitempty" tf:"jar,omitempty"`

	// Reference to a File in storage to populate jar.
	// +kubebuilder:validation:Optional
	JarRef *v1.Reference `json:"jarRef,omitempty" tf:"-"`

	// Selector for a File in storage to populate jar.
	// +kubebuilder:validation:Optional
	JarSelector *v1.Selector `json:"jarSelector,omitempty" tf:"-"`

	// Configuration block for a Maven library. The block consists of the following fields:
	// +kubebuilder:validation:Optional
	Maven []LibraryMavenParameters_2 `json:"maven,omitempty" tf:"maven,omitempty"`

	// Configuration block for management through the account provider. This block consists of the following fields:
	// +kubebuilder:validation:Optional
	ProviderConfig []LibraryProviderConfigParameters_2 `json:"providerConfig,omitempty" tf:"provider_config,omitempty"`

	// Configuration block for a PyPI library. The block consists of the following fields:
	// +kubebuilder:validation:Optional
	Pypi []LibraryPypiParameters_2 `json:"pypi,omitempty" tf:"pypi,omitempty"`

	// Path to the requirements.txt file. Only Workspace paths and Unity Catalog Volumes paths are supported. For example: /Workspace/path/to/requirements.txt or /Volumes/path/to/requirements.txt. Requires a cluster with DBR 15.0+.
	// +kubebuilder:validation:Optional
	Requirements *string `json:"requirements,omitempty" tf:"requirements,omitempty"`

	// Path to the wheel library. Supported URIs include Workspace paths, Unity Catalog Volumes paths, and S3 URIs. For example: /Workspace/path/to/library.whl, /Volumes/path/to/library.whl or s3://my-bucket/library.whl. If S3 is used, make sure the cluster has read access to the library. You may need to launch the cluster with an IAM role to access the S3 URI.
	// +crossplane:generate:reference:type=github.com/glalanne/provider-databricks/apis/cluster/storage/v1alpha1.File
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("path",false)
	// +kubebuilder:validation:Optional
	Whl *string `json:"whl,omitempty" tf:"whl,omitempty"`

	// Reference to a File in storage to populate whl.
	// +kubebuilder:validation:Optional
	WhlRef *v1.Reference `json:"whlRef,omitempty" tf:"-"`

	// Selector for a File in storage to populate whl.
	// +kubebuilder:validation:Optional
	WhlSelector *v1.Selector `json:"whlSelector,omitempty" tf:"-"`
}

type LibraryProviderConfigInitParameters_2 struct {

	// Workspace ID that the resource belongs to. This workspace must be part of the account that the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type LibraryProviderConfigObservation_2 struct {

	// Workspace ID that the resource belongs to. This workspace must be part of the account that the provider is configured with.
	WorkspaceID *string `json:"workspaceId,omitempty" tf:"workspace_id,omitempty"`
}

type LibraryProviderConfigParameters_2 struct {

	// Workspace ID that the resource belongs to. This workspace must be part of the account that the provider is configured with.
	// +kubebuilder:validation:Optional
	WorkspaceID *string `json:"workspaceId" tf:"workspace_id,omitempty"`
}

type LibraryPypiInitParameters_2 struct {

	// The name of the PyPI package to install. An optional exact version specification is also supported. For example: simplejson or simplejson==3.8.0.
	Package *string `json:"package,omitempty" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default pip index is used.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryPypiObservation_2 struct {

	// The name of the PyPI package to install. An optional exact version specification is also supported. For example: simplejson or simplejson==3.8.0.
	Package *string `json:"package,omitempty" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default pip index is used.
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

type LibraryPypiParameters_2 struct {

	// The name of the PyPI package to install. An optional exact version specification is also supported. For example: simplejson or simplejson==3.8.0.
	// +kubebuilder:validation:Optional
	Package *string `json:"package" tf:"package,omitempty"`

	// The repository where the package can be found. If not specified, the default pip index is used.
	// +kubebuilder:validation:Optional
	Repo *string `json:"repo,omitempty" tf:"repo,omitempty"`
}

// LibrarySpec defines the desired state of Library
type LibrarySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LibraryParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LibraryInitParameters_2 `json:"initProvider,omitempty"`
}

// LibraryStatus defines the observed state of Library.
type LibraryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LibraryObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Library is the Schema for the Librarys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,databricks}
type Library struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LibrarySpec   `json:"spec"`
	Status            LibraryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LibraryList contains a list of Librarys
type LibraryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Library `json:"items"`
}

// Repository type metadata.
var (
	Library_Kind             = "Library"
	Library_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Library_Kind}.String()
	Library_KindAPIVersion   = Library_Kind + "." + CRDGroupVersion.String()
	Library_GroupVersionKind = CRDGroupVersion.WithKind(Library_Kind)
)

func init() {
	SchemeBuilder.Register(&Library{}, &LibraryList{})
}
